import assert from 'node:assert/strict';import {mkdirSync} from 'node:fs';import {chromium} from 'playwright';import sharp from 'sharp';import {createApp} from '../server/app.mjs';
mkdirSync('ui-screenshots',{recursive:true});const browser=await chromium.launch();const png=await sharp({create:{width:640,height:320,channels:3,background:'#435fa1'}}).png().toBuffer();try{for(const width of [360,1440]){const app=await createApp(),origin=await app.listen(),contexts=[],errors=[];try{
 async function actor(handle,login=false){const context=await browser.newContext({viewport:{width,height:900}});contexts.push(context);let csrf;async function api(path,method='GET',body){const r=await context.request.fetch(origin+path,{method,headers:{Origin:origin,'X-Community-Request':'1',...(csrf?{'X-CSRF-Token':csrf}:{})},...(body===undefined?{}:{data:body})});assert(r.ok(),await r.text());const d=await r.json();if(d.csrf)csrf=d.csrf;return d;}const me=await api('/api/'+(login?'login':'register'),'POST',{handle,name:handle,password:'Browser-drafts-only-123'}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));return {context,page,api,id:me.user.id};}
 const owner=await actor('draft_host'),writer=await actor('draft_player');const club=await owner.api('/api/clubs','POST',{name:'Клуб вечерних обсуждений',description:'Сохраняй мысли и делись ими, когда будешь готов.',access:'request'}),root='/api/clubs/'+club.id;await writer.api(root+'/join','POST',{});await owner.api(root+'/decision','POST',{userId:writer.id,decision:'approve'});
 async function open(a){await a.page.goto(origin);await a.page.locator('.welcome-hero').waitFor();await a.page.locator('#home').click();await a.page.locator(`[data-open="${club.id}"]`).click();await a.page.locator('.club-compose summary').click();await a.page.locator('#post [name=title]').waitFor();}
 await open(writer);const p=writer.page;await p.locator('#post [name=title]').fill('После матча <img src=x>');await p.locator('#post [name=body]').fill('Хороший матч начинается с общения.\nЧто помогло вам победить сегодня?');await p.locator('#post [name=imageFile]').setInputFiles({name:'draft.png',mimeType:'image/png',buffer:png});await p.waitForFunction(async path=>(await(await fetch(path)).json()).draft?.image_id,root+'/draft');await p.locator('[data-draft-preview]').click();await p.locator('[data-draft-preview-pane]:not(.hidden) img').waitFor();assert.equal(await p.locator('[data-draft-preview-pane] img[src=x]').count(),0);assert.match(await p.locator('[data-draft-preview-pane] h3').textContent(),/<img src=x>/);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await p.screenshot({path:`ui-screenshots/draft-preview-${width}.png`,fullPage:true});assert.equal((await owner.api(root+'/posts')).posts.length,0);
 // New browser session sees the saved private draft and its protected image.
 const other=await actor('draft_player',true);assert.equal(other.id,writer.id);console.log('SAVED BEFORE RESTORE',JSON.stringify((await other.api(root+'/draft')).draft));await open(other);try{await other.page.waitForFunction(()=>document.querySelector('#post [name=title]')?.value.includes('После матча'));}catch(e){console.log('RESTORE STATE',await other.page.locator('#post').innerText(),await other.page.locator('#post [name=title]').inputValue(),JSON.stringify(await other.api(root+'/draft')));await other.page.screenshot({path:`ui-screenshots/draft-restore-failure-${width}.png`,fullPage:true});throw e;}assert.equal(await other.page.locator('.upload-preview img').count(),1);await other.page.locator('#post [name=title]').fill('Заголовок из второй вкладки');await other.page.locator('[data-draft-save]').click();await other.page.getByText('Черновик сохранён на сервере.',{exact:true}).waitFor();
 await p.locator('#post [name=body]').fill('Мой несохранённый текст');await p.locator('[data-draft-save]').click();await p.waitForFunction(()=>document.querySelector('[data-draft-status]').textContent.includes('другой вкладке'));assert.equal(await p.locator('#post [name=body]').inputValue(),'Мой несохранённый текст');p.once('dialog',d=>d.accept());await p.locator('[data-draft-reload]').click();await p.waitForFunction(()=>document.querySelector('#post [name=title]')?.value==='Заголовок из второй вкладки');
 let lost=true;await p.route('**'+root+'/draft/publish',async route=>{if(lost){lost=false;await route.fetch();await route.abort('failed');}else await route.continue();});await p.locator('#post button:not([type=button])').click();await p.getByRole('button',{name:'Проверить публикацию',exact:true}).waitFor();await p.getByRole('button',{name:'Проверить публикацию',exact:true}).click();await p.getByRole('heading',{name:'Заголовок из второй вкладки',exact:true}).waitFor();assert.equal((await owner.api(root+'/posts')).posts.length,1);assert.equal((await writer.api(root+'/draft')).draft,null);assert.equal((await writer.api('/api/drafts')).drafts.length,0);
 await p.locator('.club-compose summary').click();await p.locator('#post [name=title]').fill('Этот черновик удалится при выходе');await p.locator('#post [name=body]').fill('Текст');await p.locator('[data-draft-save]').click();await p.getByText('Черновик сохранён на сервере.',{exact:true}).waitFor();await p.locator('[data-membership=leave]').click();await p.getByText('Содержимое доступно только принятым участникам.',{exact:true}).waitFor();assert.equal((await writer.api('/api/drafts')).drafts.length,0);assert.deepEqual(errors,[]);
 console.log(`PASS ${width}px: autosave/image preview, new-session restore, private unpublished draft, cross-tab conflict, explicit reload, lost-publish retry without duplicate, membership cleanup and layout`);
 }finally{for(const c of contexts)await c.close();await app.close();}}}finally{await browser.close();}
