import assert from 'node:assert/strict';
import {mkdirSync} from 'node:fs';
import {chromium} from 'playwright';
import {createApp} from '../server/app.mjs';
const browser=await chromium.launch();mkdirSync('ui-screenshots',{recursive:true});
try{
 for(const width of [360,390,768,1440]){
  const app=await createApp(),origin=await app.listen(),contexts=[],errors=[];
  try{
   async function actor(handle){const context=await browser.newContext({viewport:{width,height:900}});contexts.push(context);let csrf='';async function api(path,method='GET',body){const r=await context.request.fetch(origin+path,{method,headers:{Origin:origin,'X-Community-Request':'1','X-CSRF-Token':csrf},...(body===undefined?{}:{data:body})});assert(r.ok(),`${path}: ${r.status()} ${await r.text()}`);const d=await r.json();if(d.csrf)csrf=d.csrf;return d;}const session=await api('/api/register','POST',{handle,name:handle==='club_owner'?'Организатор':'Модератор',password:'Browser-club-only-123'}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));return {page,api,id:session.user.id};}
   const owner=await actor('club_owner'),mod=await actor('club_mod');const club=await owner.api('/api/clubs','POST',{name:'Клуб вечерних игр',description:'Спокойно обсуждаем матчи и играем вместе.',access:'request'}),path='/api/clubs/'+club.id;
   await mod.api(path+'/join','POST',{});await owner.api(path+'/decision','POST',{userId:mod.id,decision:'approve'});
   const post=await owner.api(path+'/posts','POST',{title:'Добро пожаловать в наш клуб',body:'Расскажи, когда играешь и какие роли предпочитаешь.',clientId:'browser-club-post'});
   async function open(player){await player.page.goto(origin);await player.page.locator('.welcome-hero').waitFor();await player.page.locator('#home').click();await player.page.locator(`[data-open="${club.id}"]`).click();await player.page.locator('[data-club-tab=posts]').waitFor();}
   async function layout(page,label){assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,`${width}: overflow ${label}`);assert.equal(await page.locator('#main img[src=x]').count(),0);assert.deepEqual(errors,[]);}
   await open(owner);await owner.page.locator('[data-club-tab=settings]').click();const settings=owner.page.locator('[data-club-settings]');await settings.waitFor();
   await settings.locator('[name=rules]').fill('Уважаем друг друга. Без спама. <img src=x> — это текст. '+'ДлинноеПравило'.repeat(20));await settings.locator('[name=tags]').fill('Ранкед, Общение, Лес');await settings.locator('[name=accent]').selectOption('violet');await settings.locator('button').click();await owner.page.locator('.club-banner.accent-violet').waitFor();assert.equal(await settings.locator('[name=rules]').inputValue(),'Уважаем друг друга. Без спама. <img src=x> — это текст. '+'ДлинноеПравило'.repeat(20));
   await layout(owner.page,'settings');await owner.page.evaluate(()=>scrollTo(0,0));await owner.page.screenshot({path:`ui-screenshots/club-settings-${width}.png`,fullPage:true});
   await owner.page.locator('[data-club-tab=members]').click();await owner.page.locator(`[data-club-role="${mod.id}"]`).click();await owner.page.locator(`[data-club-role="${mod.id}"][data-role-method=DELETE]`).waitFor();
   await layout(owner.page,'members');await owner.page.evaluate(()=>scrollTo(0,0));await owner.page.screenshot({path:`ui-screenshots/club-members-${width}.png`,fullPage:true});
   await owner.page.locator('[data-club-tab=settings]').click();const inviteForm=owner.page.locator('[data-club-invite]');await inviteForm.locator('[name=maxUses]').fill('2');await inviteForm.locator('button').click();const share=inviteForm.locator('[data-invite-share] input');await share.waitFor();const link=await share.inputValue();assert(link.startsWith(origin+'/#invite='));const token=link.split('#invite=')[1];
   // A signed-out recipient follows a fragment link, registers, then applies; no content leak.
   const newcomerContext=await browser.newContext({viewport:{width,height:900}});contexts.push(newcomerContext);const newcomer=await newcomerContext.newPage();newcomer.on('pageerror',e=>errors.push(e.message));await newcomer.goto(link);await newcomer.locator('#register').waitFor();assert.equal(new URL(newcomer.url()).hash,'');
   for(const [key,value] of Object.entries({handle:'club_newcomer',name:'Новый участник',password:'Browser-club-only-123'}))await newcomer.locator(`#register [name=${key}]`).fill(value);await newcomer.locator('#register button').click();await newcomer.locator('[data-invite-accept]').waitFor();await newcomer.locator('.club-rules summary').click();await layout(newcomer,'invite rules');await newcomer.screenshot({path:`ui-screenshots/club-invite-${width}.png`,fullPage:true});await newcomer.locator('[data-invite-accept]').click();await newcomer.getByText('Содержимое доступно только принятым участникам.',{exact:true}).waitFor();assert.equal(await newcomer.locator('.post-title').count(),0);
   const newcomerSession=await (await newcomerContext.request.get(origin+'/api/me')).json();
   await open(mod);assert.equal(await mod.page.locator('[data-club-tab=settings]').count(),0);await mod.page.locator('[data-club-tab=members]').click();await mod.page.locator(`[data-user="${newcomerSession.user.id}"][data-decision=approve]`).click();await mod.page.locator(`[data-user="${newcomerSession.user.id}"][data-decision=approve]`).waitFor({state:'detached'});
   await mod.page.locator('[data-club-tab=posts]').click();await mod.page.locator(`[data-club-pin="${post.id}"]`).click();await mod.page.locator('.club-pin-list').waitFor();assert.equal((await mod.api(path+'/pins')).posts.length,1);await layout(mod.page,'pinned club');await mod.page.evaluate(()=>scrollTo(0,0));await mod.page.screenshot({path:`ui-screenshots/club-pins-${width}.png`,fullPage:true});
   await mod.page.locator('[data-club-pinned-post]').click();await mod.page.locator('[data-comment-form]').waitFor();await mod.page.locator('.back-link[data-nav=club]').click();await mod.page.locator('[data-club-tab=chat]').click();await mod.page.locator('[data-chat-form]').waitFor();await mod.page.locator('[data-chat-form] [name=body]').fill('Добро пожаловать, сыграем вечером!');await mod.page.locator('[data-chat-form] button').click();await mod.page.locator('[data-message-id]').waitFor();await layout(mod.page,'chat tab');
   // Owner offers, recipient accepts, old owner loses management. Invitation is revoked.
   await owner.page.locator('[data-club-tab=members]').click();owner.page.once('dialog',d=>d.accept());await owner.page.locator(`[data-club-transfer="${mod.id}"]`).click();await owner.page.locator('[data-club-cancel-transfer]').waitFor();await mod.page.locator('[data-club-tab=posts]').click();await mod.page.locator('[data-club-accept-transfer]').waitFor();mod.page.once('dialog',d=>d.accept());await mod.page.locator('[data-club-accept-transfer]').click();await mod.page.locator('[data-club-tab=settings]').waitFor();
   await owner.page.locator('[data-club-tab=posts]').click();await owner.page.locator('[data-club-tab=posts][aria-current=page]').waitFor();assert.equal(await owner.page.locator('[data-club-tab=settings]').count(),0);assert.equal((await mod.api(path+'/detail')).club.myRole,'owner');
   const preview=await newcomerContext.request.post(origin+'/api/club-invites/preview',{headers:{Origin:origin,'X-Community-Request':'1','X-CSRF-Token':newcomerSession.csrf},data:{token}});assert.equal(preview.status(),404);
   await mod.page.locator('[data-club-tab=members]').click();await mod.page.locator('.club-journal summary').click();await mod.page.getByText('Владение передано',{exact:true}).waitFor();await layout(mod.page,'ownership audit');
   console.log(`PASS ${width}px: settings/rules/tags/accent, role grant, fragment invite + signup, pending privacy, moderator approval/pin/chat, consensual ownership, revoked invite, audit and layout`);
  }finally{for(const c of contexts)await c.close();await app.close();}
 }
}finally{await browser.close();}
