import assert from 'node:assert/strict';import {mkdirSync} from 'node:fs';import {chromium} from 'playwright';import {createApp} from '../server/app.mjs';
mkdirSync('ui-screenshots',{recursive:true});const browser=await chromium.launch();try{for(const width of [360,1440]){let clock=Date.now();const app=await createApp({now:()=>clock}),origin=await app.listen(),contexts=[],errors=[];try{
async function actor(handle){const context=await browser.newContext({viewport:{width,height:900}});contexts.push(context);let csrf;async function api(path,method='GET',body){const r=await context.request.fetch(origin+path,{method,headers:{Origin:origin,'X-Community-Request':'1',...(csrf?{'X-CSRF-Token':csrf}:{})},...(body===undefined?{}:{data:body})});assert(r.ok(),await r.text());const d=await r.json();if(d.csrf)csrf=d.csrf;return d;}const me=await api('/api/register','POST',{handle,name:handle,password:'Browser-poll-only-123'}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));return {context,page,api,id:me.user.id};}
const host=await actor('poll_host'),voter=await actor('poll_player'),club=await host.api('/api/clubs','POST',{name:'Клуб игровых вечеров',description:'Выбираем игру вместе.',access:'request'}),root='/api/clubs/'+club.id;await voter.api(root+'/join','POST',{});await host.api(root+'/decision','POST',{userId:voter.id,decision:'approve'});
async function open(a){await a.page.goto(origin+'/feed');await a.page.locator('.welcome-hero').waitFor();await a.page.locator('#home').click();await a.page.locator(`[data-open="${club.id}"]`).click();await a.page.locator('.poll-compose summary').waitFor();}
await open(host);const p=host.page;await p.locator('.poll-compose summary').click();const form=p.locator('[data-poll-create]');await form.locator('[name=title]').fill('Что сыграем <img src=x>?');await form.locator('[name=body]').fill('Выбери режим для вечера.');await form.locator('[name=option]').nth(0).fill('Ущелье');await form.locator('[name=option]').nth(1).fill('ARAM');await form.locator('[data-poll-add]').click();await form.locator('[name=option]').nth(2).fill('Дуэль');await form.locator('[name=durationHours]').selectOption('1');assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await p.screenshot({path:`ui-screenshots/poll-editor-${width}.png`,fullPage:true});
let lostCreate=true;await p.route('**'+root+'/polls',async route=>{if(lostCreate){lostCreate=false;await route.fetch();await route.abort('failed');}else await route.continue();});await form.locator('button:not([type=button])').click();await p.getByRole('button',{name:'Проверить создание',exact:true}).waitFor();assert.equal(await form.locator('[name=title]').isDisabled(),true);await p.getByRole('button',{name:'Проверить создание',exact:true}).click();await p.locator('[data-poll]').waitFor();const posts=(await host.api(root+'/posts')).posts;assert.equal(posts.length,1);const id=posts[0].id,path='/api/posts/'+id+'/poll',card=`[data-poll="${id}"]`;assert.equal(await p.locator('img[src=x]').count(),0);assert.equal(await p.locator(`[data-edit-post="${id}"]`).count(),0);
await open(voter);const q=voter.page;let lostVote=true;await q.route('**'+path+'/vote',async route=>{if(lostVote){lostVote=false;await route.fetch();await route.abort('failed');}else await route.continue();});await q.locator(`${card} [data-option="1"]`).click();await q.locator(`${card} .poll-error`).getByText(/Голос не подтверждён/).waitFor();assert.equal(await q.locator(`${card} [data-option="0"]`).isDisabled(),true);await q.locator(`${card} [data-option="1"]`).click();await q.locator(`${card} [aria-pressed="true"]`).waitFor();assert.equal((await voter.api(path)).poll.total,1);assert.equal((await voter.api(path)).poll.myOption,1);await host.api(path+'/vote','PUT',{optionId:0});await q.locator(`${card} [data-poll-refresh]`).click();await q.locator(`${card} [role=status]`).getByText(/2 голосов/).waitFor();assert.equal(await q.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);const fill=await q.locator(`${card} [data-option="1"]`).evaluate(el=>el.querySelector('.poll-bar').getBoundingClientRect().width/el.getBoundingClientRect().width);assert.ok(fill>0.45&&fill<0.55,'50% results bar must render under the existing CSP');await q.screenshot({path:`ui-screenshots/poll-results-${width}.png`,fullPage:true});
clock+=3600000;await q.locator(`${card} [data-poll-refresh]`).click();await q.locator(card).getByText('Опрос завершён',{exact:true}).waitFor();assert.equal(await q.locator(`${card} [data-poll-vote]:not([disabled])`).count(),0);
await voter.api(root+'/leave','POST',{});await q.locator(`${card} [data-poll-refresh]`).click();await q.getByText('Публикация больше недоступна.',{exact:true}).waitFor();assert.equal(await q.locator(card).count(),0);assert.equal((await host.api(path)).poll.total,1);assert.deepEqual(errors,[]);
console.log(`PASS ${width}px: real poll creation, lost-create retry, options, immutable question, lost-vote retry without duplicate, anonymous counts, deadline, access revocation and layout`);
}finally{for(const c of contexts)await c.close();await app.close();}}}finally{await browser.close();}

