import assert from 'node:assert/strict';import {mkdirSync} from 'node:fs';import {chromium} from 'playwright';import {createApp} from '../server/app.mjs';
mkdirSync('ui-screenshots',{recursive:true});const browser=await chromium.launch();try{for(const width of [360,1440]){const app=await createApp(),origin=await app.listen(),contexts=[],errors=[];try{
 async function actor(handle,name=handle){const context=await browser.newContext({viewport:{width,height:900}});contexts.push(context);let csrf;async function api(path,method='GET',body){const r=await context.request.fetch(origin+path,{method,headers:{Origin:origin,'X-Community-Request':'1',...(csrf?{'X-CSRF-Token':csrf}:{})},...(body===undefined?{}:{data:body})});assert(r.ok(),await r.text());const d=await r.json();if(d.csrf)csrf=d.csrf;return d;}const me=await api('/api/register','POST',{handle,name,password:'Browser-home-only-123'}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));return {context,page,api,id:me.user.id};}
 const player=await actor('home_browser','Игрок <img src=x>'),owner=await actor('home_host');await player.api('/api/me','PATCH',{profileVisible:false,gameProfile:{region:'EU',language:'ru',roles:['jungle']}});
 const club=await player.api('/api/clubs','POST',{name:'Наш клуб <img src=x>',description:'Вечерние игры',access:'request'});await player.api('/api/clubs/'+club.id+'/posts','POST',{clientId:'browser-home-post-001',title:'Разговор после игры',body:'Что получилось в последнем матче?'});
 const event=await owner.api('/api/events','POST',{clientId:'browser-home-event-001',title:'Вечерний состав',description:'Играем вместе',mode:'ranked',region:'EU',language:'ru',timezone:'UTC',startsAt:Date.now()+3600000,durationHours:1,roles:['mid','jungle'],ownerRole:'mid'});await player.api('/api/events/'+event.id+'/join','POST',{role:'jungle'});
 const group=await owner.api('/api/lfg','POST',{clientId:'browser-home-group-001',title:'Ищем лесника сейчас',mode:'normal',region:'EU',language:'ru',role:'jungle',rank:'',voice:'optional',description:'Без спешки',capacity:3,durationHours:2});
 const p=player.page;async function home(){await p.locator('#discover').click();await p.locator('.home-plans').waitFor();}await p.goto(origin);await p.locator('.home-plans').waitFor();assert.equal(await p.locator('#main img[src=x]').count(),0);await p.locator(`[data-home-event="${event.id}"]`).waitFor();await p.locator(`[data-home-group="${group.id}"]`).waitFor();assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.match(await p.locator('.home-matches .note').first().textContent(),/регион: EU/);await p.screenshot({path:`ui-screenshots/home-personal-${width}.png`,fullPage:true});
 await p.locator(`[data-home-event="${event.id}"]`).click();await p.locator('#eventChat [data-chat-form]').waitFor();await home();await p.locator(`[data-home-group="${group.id}"]`).click();await p.getByRole('heading',{name:'Ищем лесника сейчас',exact:true}).waitFor();assert.equal(await p.locator('[data-chat-form]').count(),0);
 await home();await p.locator('[data-home-compose]').click();await p.locator('.club-compose[open] #post').waitFor();await p.locator('#post [name=title]').fill('Публикация с главной');await p.locator('#post [name=body]').fill('Быстрый редактор работает');await p.locator('#post button').click();await p.getByRole('heading',{name:'Публикация с главной',exact:true}).waitFor();
 await home();await p.locator('[data-home-create-event]').first().click();await p.locator('.event-create[open] [data-event-create]').waitFor();await home();await p.locator('[data-home-create-group]').first().click();await p.locator('details[open] [data-lfg-create]').waitFor();
 await owner.api('/api/events/'+event.id+'/remove','POST',{userId:player.id});await home();assert.equal(await p.locator(`[data-home-event="${event.id}"]`).count(),0);await player.api('/api/clubs/'+club.id+'/settings','PATCH',{version:0,name:'Наш клуб',description:'Вечерние игры',rules:'',tags:[],accent:'azure'}); // Current settings are reflected, no cached home copy.
 await home();assert.match(await p.locator(`.home-clubs [data-open="${club.id}"]`).textContent(),/Наш клуб/);assert.deepEqual(errors,[]);
 const guest=await browser.newContext({viewport:{width,height:900}});contexts.push(guest);const gp=await guest.newPage();await gp.goto(origin);await gp.locator('.welcome-hero').waitFor();assert.equal(await gp.locator('.home-plans').count(),0);assert.equal(await gp.locator('[data-home-compose]').count(),0);
 console.log(`PASS ${width}px: private personal home, profile matching, direct event/group links, post/event/group editors, membership revocation, escaped content, guest page and layout`);
 }finally{for(const c of contexts)await c.close();await app.close();}}}finally{await browser.close();}
