const {JSDOM,VirtualConsole}=require('jsdom');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const {pathToFileURL}=require('node:url');
(async()=>{const {createApp}=await import(pathToFileURL(path.join(__dirname,'../server/app.mjs')).href);const app=await createApp(),origin=await app.listen();let dom,controller;try{
 const client=()=>({cookie:'',csrf:'',async api(p,m='GET',body){const r=await fetch(origin+p,{method:m,headers:{Cookie:this.cookie,...(m!=='GET'?{Origin:origin,'X-Community-Request':'1','X-CSRF-Token':this.csrf,'Content-Type':'application/json'}:{})},body:body===undefined?undefined:JSON.stringify(body)}),d=await r.json();if(r.headers.has('set-cookie'))this.cookie=r.headers.get('set-cookie').split(';')[0];if(d.csrf)this.csrf=d.csrf;if(d.user)this.id=d.user.id;if(!r.ok){const e=new Error(d.error);e.status=r.status;throw e;}return d;}});
 const a=client(),b=client();for(const[c,handle]of[[a,'actions_ui_a'],[b,'actions_ui_b']])await c.api('/api/register','POST',{handle,name:handle,password:'Actions-ui-pass-123'});
 const club=(await a.api('/api/clubs','POST',{name:'Actions UI',description:'',access:'open'})).id;await b.api(`/api/clubs/${club}/join`,'POST',{});const endpoint=`/api/clubs/${club}/messages`,source=(await b.api(endpoint,'POST',{clientId:'actions-ui-source-0001',body:'Source <img src=x>'})).message,own=(await a.api(endpoint,'POST',{clientId:'actions-ui-own-000001',body:'Own message'})).message;
 const errors=[],vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));dom=new JSDOM('<section id=root></section>',{url:origin,runScripts:'outside-only',virtualConsole:vc});const w=dom.window,d=w.document,root=d.querySelector('#root');w.confirm=()=>true;w.eval(fs.readFileSync(path.join(__dirname,'../server/public/chat.js'),'utf8'));
 let dropAction=null;const api=async(...args)=>{const data=await a.api(...args);if(args[0].endsWith('/'+dropAction)&&args[1]==='POST'){dropAction=null;throw new TypeError('Lost response after commit');}return data;};
 const mount=()=>controller=w.createClubChat({root,clubId:club,userId:a.id,api});mount();const q=s=>root.querySelector(s);const until=async fn=>{for(let i=0;i<600;i++){if(fn())return;await new Promise(r=>setTimeout(r,10));}throw Error('Timeout '+root.textContent);};const input=(el,value)=>{el.value=value;el.dispatchEvent(new w.Event('input',{bubbles:true}));};const submit=el=>el.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));
 await until(()=>q(`[data-message-id="${own.id}"]`));input(q('[data-chat-form] textarea'),'Composer draft stays');q(`[data-chat-edit="${own.id}"]`).click();input(q('[name=editBody]'),'Edited <img src=x>');q('[name=editBody]').dispatchEvent(new w.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));assert(!q('dialog').hasAttribute('open'));assert.equal(q('[data-chat-form] textarea').value,'Composer draft stays');
 controller.destroy();mount();await until(()=>q(`[data-chat-edit="${own.id}"]`));q(`[data-chat-edit="${own.id}"]`).click();assert.equal(q('[name=editBody]').value,'Edited <img src=x>');dropAction='edit';submit(q('[data-chat-action-form]'));await until(()=>q('[data-mutation-retry]')&&!q('[data-mutation-retry]').disabled);q('[data-mutation-retry]').click();await until(()=>!q('[data-mutation-retry]'));assert.equal((await a.api(endpoint+'/'+own.id)).message.version,2);assert.equal(q('[data-chat-form] textarea').value,'Composer draft stays');assert(root.textContent.includes('Edited <img src=x>'));assert.equal(root.querySelectorAll('img').length,0);
 q(`[data-chat-reply="${source.id}"]`).click();assert.equal(q('[data-chat-form] textarea').value,'Composer draft stays');input(q('[data-chat-form] textarea'),'Quoted response');controller.destroy();mount();await until(()=>q('.chat-reply-context')&&!q('.chat-reply-context').hidden);assert.equal(q('[data-chat-form] textarea').value,'Quoted response');submit(q('[data-chat-form]'));await until(()=>root.textContent.includes('Quoted response')&&!q('[data-chat-retry]'));const reply=(await a.api(endpoint)).messages.find(m=>m.body==='Quoted response');assert.equal(reply.reply.id,source.id);assert(q(`[data-message-id="${reply.id}"] .chat-quote`).textContent.includes('Source <img src=x>'));
 dropAction='reaction';assert(q(`[data-chat-reaction="${source.id}"]`),root.innerHTML);[...root.querySelectorAll(`[data-chat-reaction="${source.id}"]`)].find(el=>el.dataset.emoji==='👍').click();await until(()=>q('[data-mutation-retry]')&&!q('[data-mutation-retry]').disabled);controller.destroy();mount();await until(()=>q('[data-mutation-retry]')&&!q('[data-mutation-retry]').disabled);q('[data-mutation-retry]').click();await until(()=>!q('[data-mutation-retry]'));assert.equal((await a.api(endpoint+'/'+source.id)).message.reactions[0].count,1);
 await b.api('/api/blocks','POST',{userId:a.id});q('[data-chat-refresh]').click();await until(()=>!root.textContent.includes('Source <img src=x>'));await b.api('/api/blocks','DELETE',{userId:a.id});q('[data-chat-refresh]').click();await until(()=>root.textContent.includes('Source <img src=x>'));
 await b.api(endpoint+'/'+source.id+'/delete','POST',{clientId:'actions-ui-delete-0001',version:1});q('[data-chat-refresh]').click();await until(()=>q(`[data-message-id="${reply.id}"] .chat-quote`).textContent.includes('недоступно'));assert(!root.textContent.includes('Source <img src=x>'));
 q(`[data-chat-delete="${own.id}"]`).click();assert(q('dialog').textContent.includes('у всех участников'));q('[data-chat-dialog-cancel]').click();assert.equal((await a.api(endpoint+'/'+own.id)).message.deleted,false);q(`[data-chat-delete="${own.id}"]`).click();submit(q('[data-chat-action-form]'));await until(()=>q(`[data-message-id="${own.id}"]`).textContent.includes('Сообщение удалено'));assert(!q(`[data-message-id="${own.id}"] [data-chat-edit]`));assert.deepEqual(errors,[]);console.log('PASS: quoted replies, reactions and edits/deletions, lost responses, remount, Escape, independent drafts and deleted source refresh');
}finally{controller?.destroy();dom?.window.close();await app.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
