const {JSDOM,VirtualConsole}=require('jsdom'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {pathToFileURL}=require('node:url');const os=require('node:os');
(async()=>{
 const {createApp}=await import(pathToFileURL(path.join(__dirname,'../server/app.mjs')).href),temp=fs.mkdtempSync(path.join(os.tmpdir(),'wr-notice-ui-')),databasePath=path.join(temp,'db.sqlite'),app=await createApp({databasePath}),origin=await app.listen();let dom,failCenter=false;
 const client=()=>({cookie:'',csrf:'',async req(url,method='GET',body){const r=await fetch(origin+url,{method,headers:{Cookie:this.cookie,Origin:origin,'Content-Type':'application/json','X-Community-Request':'1','X-CSRF-Token':this.csrf},body:body?JSON.stringify(body):undefined}),data=await r.json();if(r.headers.get('set-cookie'))this.cookie=r.headers.get('set-cookie').split(';')[0];if(data.csrf)this.csrf=data.csrf;assert.equal(r.ok,true,JSON.stringify(data));return data;}});
 try{
  const owner=client(),captain=client(),player=client();for(const [c,handle] of [[owner,'ui_notice_owner'],[captain,'ui_notice_captain'],[player,'ui_notice_player']])await c.req('/api/register','POST',{handle,name:handle,password:'Notice-UI-test-only-123'});
  await player.req('/api/me','PATCH',{profileVisible:true});
  async function invite(clientId){const {id}=await owner.req('/api/tournaments','POST',{title:'Cup <img src=x>',capacity:4,clientId});await captain.req('/api/tournaments/'+id+'/join','POST',{name:'Team <svg>'});await captain.req('/api/tournaments/'+id+'/invite','POST',{handle:'ui_notice_player'});return id;}
  const {openDatabase:fixtureDB}=await import(pathToFileURL(path.join(__dirname,'../server/database.mjs')).href),seed=fixtureDB(databasePath);try{const o=seed.prepare('SELECT id FROM users WHERE handle=?').get('ui_notice_owner').id,p=seed.prepare('SELECT id FROM users WHERE handle=?').get('ui_notice_player').id;
   seed.prepare("INSERT INTO game_events(id,owner_id,client_id,signature,title,description,mode,region,language,timezone,starts_at,ends_at,created_at) VALUES(42,?,'center-ui-event','s','Event <img>','','ranked','EU','ru','UTC',9999999999999,9999999999999,100)").run(o);seed.prepare("INSERT INTO event_slots VALUES(42,'baron',?)").run(o);seed.prepare("INSERT INTO event_notifications(user_id,event_id,kind,created_at) VALUES(?,42,'joined',100)").run(p);
   seed.prepare("INSERT INTO lfg_groups(id,owner_id,title,mode,region,language,role,rank,voice,description,capacity,starts_at,expires_at,created_at,client_id,create_signature) VALUES(43,?,'Group <svg>','ranked','eu','ru','any','','none','',2,0,9999999999999,100,'center-ui-group','s')").run(o);seed.prepare("INSERT INTO lfg_members(group_id,user_id,status) VALUES(43,?,'accepted')").run(o);seed.prepare("INSERT INTO lfg_notifications(user_id,group_id,kind,created_at) VALUES(?,43,'accepted',100)").run(p);
  }finally{seed.close();}
  const id=await invite('notice-ui-first-fixture'),errors=[],vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));
  dom=new JSDOM(fs.readFileSync(path.join(__dirname,'../server/public/index.html'),'utf8'),{url:origin+'/notifications',runScripts:'outside-only',pretendToBeVisual:true,virtualConsole:vc,beforeParse(w){w.AbortController=AbortController;w.scrollTo=()=>{};w.confirm=()=>true;w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;};w.fetch=async(p,opts={})=>{if(failCenter&&p.startsWith('/api/notifications?'))throw TypeError('Offline fixture');return fetch(origin+p,{...opts,headers:{...opts.headers,Cookie:player.cookie,...(opts.method&&opts.method!=='GET'?{Origin:origin}:{})}});};}});
  const w=dom.window,d=w.document;for(const file of ['profiles.js','discussions.js','clubs.js','tournaments.js','events.js','lfg.js','app.js'])w.eval(fs.readFileSync(path.join(__dirname,'../server/public',file),'utf8'));
  async function until(fn){for(let i=0;i<300;i++){if(fn())return;await new Promise(r=>setTimeout(r,10));}throw Error('UI timeout: '+d.querySelector('#main').textContent);}
  await until(()=>d.querySelector('[data-tournament-invitation]'));assert.equal(d.querySelector('#main img'),null);assert.equal(d.querySelector('#main svg'),null);
  d.dispatchEvent(new w.Event('visibilitychange'));await until(()=>d.querySelector('#notifications').title.includes('приглашений: 1'));assert.equal(d.querySelector('[data-notification-total]').hidden,false);
  failCenter=true;d.querySelector('[data-center-refresh]').click();await until(()=>d.querySelector('[data-center-error]')?.textContent.includes('Не удалось загрузить'));failCenter=false;d.querySelector('[data-center-refresh]').click();await until(()=>d.querySelector('[data-tournament-invitation]'));
  assert.ok(d.querySelector('[data-notification-read-all]'));d.querySelector('[data-notification-read-all]').click();await until(()=>!d.querySelector('[data-notification-read-all]').disabled);assert.ok(d.querySelector('[data-tournament-invitation]'));assert.equal((await player.req('/api/notifications/summary')).notificationTotal,1);
  let filter=d.querySelector('[data-notification-type]');filter.value='events';filter.dispatchEvent(new w.Event('change',{bubbles:true}));await until(()=>d.querySelector('[data-source="events"]'));assert.equal(d.querySelector('[data-source="invitations"]'),null);d.querySelector('[data-source="events"] a').click();await until(()=>d.querySelector('[data-event-refresh]'));assert.equal(w.location.pathname,'/events');assert.equal(w.location.search,'?id=42');assert.match(d.querySelector('#eventsRoot').textContent,/Event <img>/);
  d.querySelector('#notifications').click();await until(()=>d.querySelector('[data-source="lfg"]'));d.querySelector('[data-source="lfg"] a').click();await until(()=>d.querySelector('[data-lfg-back]'));assert.equal(w.location.pathname,'/teams');assert.equal(w.location.search,'?id=43');assert.match(d.querySelector('#lfgRoot').textContent,/Group <svg>/);
  d.querySelector('#notifications').click();await until(()=>d.querySelector('[data-tournament-invitation]'));d.querySelector('[data-tournament-invitation] a').click();await until(()=>d.querySelector('[data-tournament-accept]'));
  assert.equal(w.location.pathname,'/tournaments');assert.equal(w.location.search,'?id='+id);assert.match(d.querySelector('#main').textContent,/Приглашение в Team/);
  d.querySelector('[data-tournament-accept]').click();await until(()=>d.querySelector('[data-tournament-member-leave]'));await until(()=>d.querySelector('#notifications').title.includes('приглашений: 0'));assert.equal(d.querySelector('[data-notification-total]').hidden,true);
  d.querySelector('[data-tournament-member-leave]').click();await until(()=>d.querySelector('[data-tournament-join]'));
  await captain.req('/api/tournaments/'+id+'/invite','POST',{handle:'ui_notice_player',clientId:'ui-roster-reinvite-35'});d.querySelector('[data-tournament-refresh]').click();await until(()=>d.querySelector('[data-tournament-accept]'));d.querySelector('[data-tournament-accept]').click();await until(()=>d.querySelector('[data-tournament-member-leave]'));assert.match(d.querySelector('[data-roster-history]').textContent,/Вышел из команды/);assert.match(d.querySelector('[data-roster-history]').textContent,/Приглашён/);
  const next=await invite('notice-ui-second-fixture');d.querySelector('#notifications').click();await until(()=>d.querySelector('[data-tournament-invitation="'+next+'"]'));
  await owner.req('/api/tournaments/'+next+'/cancel','POST',{reason:'Not enough players'});d.querySelector('#notifications').click();await until(()=>!d.querySelector('[data-tournament-invitation]')&&d.querySelector('#discussionEvents'));
  const {openDatabase}=await import(pathToFileURL(path.join(__dirname,'../server/database.mjs')).href),db=openDatabase(databasePath);
  try{const opponent=Number(db.prepare("INSERT INTO tournament_teams(tournament_id,captain_id,name) VALUES(?,(SELECT id FROM users WHERE handle='ui_notice_owner'),'Opponent')").run(id).lastInsertRowid),team=db.prepare('SELECT id FROM tournament_teams WHERE tournament_id=? AND captain_id=(SELECT id FROM users WHERE handle=?)').get(id,'ui_notice_captain').id;
   db.prepare("UPDATE tournaments SET state='running' WHERE id=?").run(id);db.prepare('INSERT INTO tournament_matches(tournament_id,round,slot,team_a,team_b) VALUES(?,1,0,?,?)').run(id,team,opponent);
  }finally{db.close();}
  await owner.req('/api/tournaments/'+id+'/schedule','POST',{round:1,slot:0,startsAt:Date.now()+1200000,expectedVersion:0});
  d.querySelector('#notifications').click();await until(()=>d.querySelectorAll('[data-match-notification]').length===2);assert.match(d.querySelector('#discussionEvents').textContent,/Матч назначен/);assert.match(d.querySelector('#discussionEvents').textContent,/30 минут/);
  d.dispatchEvent(new w.Event('visibilitychange'));await until(()=>d.querySelector('#notifications').title.includes('о матчах: 2'));
  d.querySelector('[data-match-read]').click();await until(()=>d.querySelectorAll('[data-match-read]').length===1);await until(()=>d.querySelector('#notifications').title.includes('о матчах: 1'));
  d.querySelector('[data-match-notification] a').click();await until(()=>d.querySelector('[data-tournament-refresh]'));assert.equal(w.location.search,'?id='+id+'&round=1&slot=0');assert.equal(d.querySelector('[data-tournament-schedule]'),null);assert.equal(d.querySelector('[data-tournament-ready]'),null);
  const r=await fetch(origin+'/api/tournaments/'+id+'/ready',{method:'POST',headers:{Cookie:captain.cookie,Origin:origin,'Content-Type':'application/json','X-Community-Request':'1'},body:JSON.stringify({round:1,slot:0,expectedVersion:1})});assert.equal(r.status,403);
  await captain.req('/api/tournaments/'+id+'/ready','POST',{round:1,slot:0,expectedVersion:1});d.querySelector('[data-tournament-refresh]').click();await until(()=>d.querySelector('[data-tournament-readiness]')?.textContent.includes('Team <svg> · Готова'));
  assert.deepEqual(errors,[]);console.log('PASS invitation center with real HTTP: private list, escaped content, exact tournament deep link, consent, combined badge reset and cancelled invitation removal. DOM only.');
 }finally{dom?.window.close();await app.close();fs.rmSync(temp,{recursive:true,force:true});}
})().catch(e=>{console.error(e);process.exitCode=1;});
