const {JSDOM,VirtualConsole}=require('jsdom'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');const {pathToFileURL}=require('node:url');
(async()=>{
 const {createApp}=await import(pathToFileURL(path.join(__dirname,'../server/app.mjs')).href);const app=await createApp(),origin=await app.listen(),windows=[],errors=[];
 try{
  async function register(handle){const r=await fetch(origin+'/api/register',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json','X-Community-Request':'1'},body:JSON.stringify({handle,name:handle,password:'Test-lfg-password-123'})});assert.equal(r.status,201);return {cookie:r.headers.get('set-cookie').split(';')[0],...(await r.json())};}
  const owner=await register('lfgowner'),member=await register('lfgmember');
  const published=await fetch(origin+'/api/me',{method:'PATCH',headers:{Origin:origin,Cookie:owner.cookie,'Content-Type':'application/json','X-Community-Request':'1','X-CSRF-Token':owner.csrf},body:JSON.stringify({name:'Напарник <img src=x>',profileVisible:true,gameProfile:{rank:'Мастер',region:'Европа',language:'Русский',roles:['mid'],microphone:'yes'}})});assert.equal(published.status,200);
  function mount(c){const vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));const dom=new JSDOM(fs.readFileSync(path.join(__dirname,'../server/public/index.html'),'utf8'),{url:origin+'/feed',runScripts:'outside-only',pretendToBeVisual:true,virtualConsole:vc});const w=dom.window;w.scrollTo=()=>{};windows.push(w);w.AbortController=AbortController;w.confirm=()=>true;w.fetch=(p,o={})=>fetch(origin+p,{...o,headers:{...o.headers,Cookie:c.cookie,...(o.method&&o.method!=='GET'?{Origin:origin}:{})}});for(const f of ['clubs.js','discussions.js','chat.js','direct.js','lfg.js','players.js','profiles.js','app.js'])w.eval(fs.readFileSync(path.join(__dirname,'../server/public',f),'utf8'));return w;}
  async function until(fn){for(let i=0;i<600;i++){if(fn())return;await new Promise(r=>setTimeout(r,10));}throw new Error(windows.map(w=>w.document.querySelector('#main').textContent).join(' | '));}
  const a=mount(owner),b=mount(member),ad=a.document,bd=b.document;
  await until(()=>ad.querySelector('.welcome-hero')&&bd.querySelector('.welcome-hero'));ad.querySelector('#lfg').click();await until(()=>ad.querySelector('[data-lfg-create]'));
  assert.equal(ad.querySelector('[data-lfg-create]').closest('details').open,false);ad.querySelector('[data-lfg-create-open]').click();assert.equal(ad.querySelector('[data-lfg-create]').closest('details').open,true);assert.equal(ad.activeElement,ad.querySelector('[data-lfg-create] input'));
  const form=ad.querySelector('[data-lfg-create]');Object.entries({title:'Группа интерфейса',region:'eu',language:'ru',description:'<img src=x> Тест',capacity:'2',rank:'Мастер',voice:'required',role:'mid'}).forEach(([k,v])=>form.elements[k].value=v);form.dispatchEvent(new a.Event('submit',{bubbles:true,cancelable:true}));await until(()=>ad.querySelector('[data-lfg-chat]'));
  bd.querySelector('#lfg').click();await until(()=>bd.querySelector('[data-lfg-filter]'));assert.equal(bd.querySelector('.group-more-filters').open,false);
  const filter=bd.querySelector('[data-lfg-filter]');filter.querySelector('summary').click();for(const [key,value] of Object.entries({rank:'МАСТЕР',voice:'required',role:'mid'}))filter.elements[key].value=value;filter.dispatchEvent(new b.Event('submit',{bubbles:true,cancelable:true}));await until(()=>bd.querySelector('.group-more-filters[open]')&&bd.querySelector('.group-list-card'));assert.equal(bd.querySelectorAll('.group-list-card').length,1);
  bd.querySelector('[data-lfg-tab=players]').click();await until(()=>bd.querySelector('[data-players-list][aria-busy=false]'));assert.equal(bd.querySelectorAll('[data-player-card]').length,1);assert(bd.querySelector('[data-player-card]').textContent.includes('Напарник <img src=x>'));assert.equal(bd.querySelector('img[src=x]'),null);
  const playerFilter=bd.querySelector('[data-player-filter]');playerFilter.querySelector('summary').click();for(const [key,value] of Object.entries({rank:'МАСТЕР',role:'mid',microphone:'yes'}))playerFilter.elements[key].value=value;playerFilter.dispatchEvent(new b.Event('submit',{bubbles:true,cancelable:true}));await until(()=>bd.querySelector('[data-players-list][aria-busy=false]')&&bd.querySelector('.advanced-filters[open]'));assert.equal(bd.querySelectorAll('[data-player-card]').length,1);
  bd.querySelector('[data-lfg-tab=groups]').click();await until(()=>bd.querySelector('.group-list-card'));assert.equal(bd.querySelector('[data-lfg-filter] [name=rank]').value,'МАСТЕР');assert.equal(bd.querySelector('.group-more-filters').open,true);bd.querySelector('[data-lfg-open]').click();await until(()=>bd.querySelector('[data-lfg-action=apply]'));bd.querySelector('[data-lfg-action=apply]').click();await until(()=>bd.querySelector('[data-lfg-action=leave]'));assert.equal(bd.querySelector('[data-lfg-chat]'),null);
  ad.querySelector('[data-lfg-refresh]').click();await until(()=>ad.querySelector('[data-lfg-decision=accept]'));ad.querySelector('[data-lfg-decision=accept]').click();await until(()=>!ad.querySelector('[data-lfg-decision=accept]')&&ad.body.textContent.includes('Группа заполнена'));
  bd.querySelector('[data-lfg-refresh]').click();await until(()=>bd.querySelector('[data-chat-form] textarea')&&!bd.querySelector('[data-chat-form] textarea').disabled);const chat=bd.querySelector('[data-chat-form]');chat.elements.body.value='Готов';chat.dispatchEvent(new b.Event('submit',{bubbles:true,cancelable:true}));await until(()=>bd.querySelector('[data-message-id]'));assert.equal(bd.querySelectorAll('#main img').length,0);
  ad.querySelector('[data-lfg-action=close]').click();await until(()=>ad.body.textContent.includes('Чат группы · только чтение'));bd.querySelector('[data-lfg-refresh]').click();await until(()=>bd.querySelector('[data-chat-form] textarea')?.disabled);await until(()=>bd.querySelector('[data-message-id]'));
  bd.querySelector('[data-lfg-action=leave]').click();await until(()=>!bd.querySelector('[data-lfg-chat]') && bd.querySelector('[data-lfg-back]'));bd.querySelector('[data-lfg-back]').click();await until(()=>bd.querySelector('[data-lfg-read]'));assert.equal(bd.querySelector('.group-notifications').open,false);bd.querySelector('.group-notifications summary').click();assert.equal(bd.querySelector('.group-notifications').open,true);assert.equal(bd.querySelector('[data-lfg-filter] [name=rank]').value,'МАСТЕР');assert(bd.querySelector('[data-lfg-notifications]').textContent.includes('Тебя приняли'));assert(bd.querySelector('[data-lfg-notifications]').textContent.includes('Автор закрыл'));await until(()=>bd.querySelector('#lfg .nav-count'));const n=bd.querySelectorAll('[data-lfg-read]').length;bd.querySelector('[data-lfg-read]').click();await until(()=>bd.querySelectorAll('[data-lfg-read]').length===n-1);assert.deepEqual(errors,[]);console.log('PASS: compact forms/focus, restored group/player filters, published profiles/privacy and escaping; create → apply → accept → private group chat → close/read-only → leave, notification badge, private event list and read marker, with escaped content. DOM only.');
 }finally{for(const w of windows)w.close();await app.close();}
})().catch(e=>{console.error(e);process.exitCode=1});

