const {JSDOM,VirtualConsole}=require('jsdom'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
(async()=>{
 const {createApp}=await import('../server/app.mjs'),app=await createApp(),origin=await app.listen(),windows=[];
 const client=()=>({cookie:'',csrf:'',async req(p,m='GET',body){const r=await fetch(origin+p,{method:m,headers:{Cookie:this.cookie,Origin:origin,'Content-Type':'application/json','X-Community-Request':'1','X-CSRF-Token':this.csrf},body:body?JSON.stringify(body):undefined}),d=await r.json();if(r.headers.get('set-cookie'))this.cookie=r.headers.get('set-cookie').split(';')[0];if(d.csrf)this.csrf=d.csrf;assert.ok(r.ok,JSON.stringify(d));return d;}});
 try{
  const owner=client(),stranger=client();for(const [c,handle] of [[owner,'route_owner'],[stranger,'route_stranger']])await c.req('/api/register','POST',{handle,name:handle,password:'Search-routing-123'});
  const club=await owner.req('/api/clubs','POST',{name:'Приватный клуб',description:'Только участники',access:'request'}),query='Ренгар & <img>',post=await owner.req('/api/clubs/'+club.id+'/posts','POST',{title:query,body:'PRIVATE ROUTE CONTENT',clientId:'search-route-post-001'});
  const html=fs.readFileSync(path.join(__dirname,'../server/public/index.html'),'utf8');
  function mount(url,c){const errors=[],vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));const dom=new JSDOM(html,{url,runScripts:'outside-only',pretendToBeVisual:true,virtualConsole:vc,beforeParse(w){w.AbortController=AbortController;w.scrollTo=()=>{};w.confirm=()=>true;w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;};w.fetch=(p,o={})=>fetch(origin+p,{...o,headers:{...o.headers,Cookie:c.cookie,...(o.method&&o.method!=='GET'?{Origin:origin}:{})}});}});windows.push(dom);const w=dom.window;for(const [,file]of html.matchAll(/<script[^>]+src="\/([\w-]+\.js)"/g))w.eval(fs.readFileSync(path.join(__dirname,'../server/public',file),'utf8'));return {w,d:w.document,errors};}
  async function until(fn,d){for(let i=0;i<300;i++){if(fn())return;await new Promise(r=>setTimeout(r,10));}throw Error('UI timeout: '+d.querySelector('#main').textContent);}
  const url=origin+'/search?'+new URLSearchParams({q:query,club:club.id}),a=mount(url,owner);await until(()=>a.d.querySelector('#searchPosts .post-title'),a.d);assert.equal(a.d.querySelector('[name=query]').value,query);assert.equal(a.d.querySelector('[name=club]').value,club.id);assert.equal(a.d.querySelector('#main img[src=x]'),null);assert.equal(new URL(a.w.location.href).searchParams.get('q'),query);
  const form=a.d.querySelector('[data-post-search]');form.elements.query.value='PRIVATE ROUTE';form.dispatchEvent(new a.w.Event('submit',{bubbles:true,cancelable:true}));await until(()=>new URL(a.w.location.href).searchParams.get('q')==='PRIVATE ROUTE'&&a.d.querySelector('#searchPosts .post-title'),a.d);
  a.w.history.back();await until(()=>a.d.querySelector('[name=query]')?.value===query&&a.d.querySelector('#searchPosts .post-title'),a.d);a.w.history.forward();await until(()=>a.d.querySelector('[name=query]')?.value==='PRIVATE ROUTE'&&a.d.querySelector('#searchPosts .post-title'),a.d);
  const reload=mount(a.w.location.href,owner);await until(()=>reload.d.querySelector('#searchPosts .post-title'),reload.d);assert.equal(reload.d.querySelector('[name=query]').value,'PRIVATE ROUTE');assert.equal(reload.d.querySelector('[name=club]').value,club.id);
  const denied=mount(url,stranger);await until(()=>denied.d.querySelector('#main').getAttribute('aria-busy')==='false',denied.d);assert.ok(!denied.d.querySelector('#main').textContent.includes('PRIVATE ROUTE CONTENT'));assert.equal(denied.d.querySelector('#searchPosts .post-title'),null);
  assert.deepEqual([...a.errors,...reload.errors,...denied.errors],[]);console.log('PASS search routing real HTTP DOM: signed-in deep link, Unicode escaping, submit, back/forward, reload and private-club denial.');
 }finally{for(const dom of windows)dom.window.close();await app.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
