const {JSDOM,VirtualConsole}=require('jsdom'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');const {pathToFileURL}=require('node:url');
(async()=>{const {createApp}=await import(pathToFileURL(path.join(__dirname,'../server/app.mjs')).href),{openDatabase}=await import(pathToFileURL(path.join(__dirname,'../server/database.mjs')).href),temp=fs.mkdtempSync(path.join(os.tmpdir(),'wr-cup-ui-')),databasePath=path.join(temp,'db'),app=await createApp({databasePath}),origin=await app.listen();let dom;
 const client=()=>({cookie:'',csrf:'',async req(url,method='GET',body){const r=await fetch(origin+url,{method,headers:{Cookie:this.cookie,Origin:origin,'Content-Type':'application/json','X-Community-Request':'1','X-CSRF-Token':this.csrf},body:body?JSON.stringify(body):undefined}),d=await r.json();if(r.headers.get('set-cookie'))this.cookie=r.headers.get('set-cookie').split(';')[0];if(d.csrf)this.csrf=d.csrf;assert.equal(r.ok,true,JSON.stringify(d));return d;}});
 try{const owner=client(),captain=client(),other=client();for(const [c,handle] of [[owner,'cup_owner'],[captain,'cup_captain'],[other,'cup_other']])await c.req('/api/register','POST',{handle,name:handle,password:'Cup-UI-test-only-123'});const id=(await owner.req('/api/tournaments','POST',{title:'Cup <svg>',capacity:4,clientId:'cup-ui-fixture-33'})).id;await captain.req('/api/tournaments/'+id+'/join','POST',{name:'Alpha <img>'});await other.req('/api/tournaments/'+id+'/join','POST',{name:'Beta'});
 const db=openDatabase(databasePath);try{const teams=db.prepare('SELECT id FROM tournament_teams WHERE tournament_id=? ORDER BY id').all(id);db.prepare("UPDATE tournaments SET state='running' WHERE id=?").run(id);db.prepare('INSERT INTO tournament_matches(tournament_id,round,slot,team_a,team_b) VALUES(?,1,0,?,?)').run(id,teams[0].id,teams[1].id);}finally{db.close();}
 const errors=[],vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));dom=new JSDOM(fs.readFileSync(path.join(__dirname,'../server/public/index.html'),'utf8'),{url:origin+'/tournaments?id='+id,runScripts:'outside-only',pretendToBeVisual:true,virtualConsole:vc,beforeParse(w){w.AbortController=AbortController;w.scrollTo=()=>{};w.confirm=()=>true;w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;};w.fetch=async(p,o={})=>fetch(origin+p,{...o,headers:{...o.headers,Cookie:owner.cookie,...(o.method&&o.method!=='GET'?{Origin:origin}:{})}});}});const w=dom.window,d=w.document;for(const file of ['profiles.js','discussions.js','clubs.js','tournaments.js','app.js'])w.eval(fs.readFileSync(path.join(__dirname,'../server/public',file),'utf8'));
 async function until(fn){for(let i=0;i<300;i++){if(fn())return;await new Promise(r=>setTimeout(r,10));}throw Error('UI timeout: '+d.querySelector('#main').textContent);}
 await until(()=>d.querySelector('[data-tournament-forfeit]'));assert.equal(d.querySelector('#main img'),null);assert.equal(d.querySelector('#main svg'),null);
 let f=d.querySelector('[data-tournament-forfeit]');f.elements.reason.value='Opponent did not arrive';f.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await until(()=>d.querySelector('[data-tournament-correct]'));assert.match(d.querySelector('#main').textContent,/Техническое поражение/);
 f=d.querySelector('[data-tournament-correct]');f.elements.scoreA.value='2';f.elements.scoreB.value='1';f.elements.reason.value='Original ruling was incorrect';f.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await until(()=>d.querySelector('[data-tournament-history]')?.textContent.includes('Original ruling was incorrect'));assert.match(d.querySelector('#main').textContent,/Победитель — Alpha/);
 d.querySelector('[data-tournament-back]').click();await until(()=>d.querySelector('[data-tournament-mine]'));d.querySelector('[data-tournament-mine]').click();await until(()=>d.querySelector('[data-my-tournaments]'));assert.match(d.querySelector('[data-my-tournaments]').textContent,/Победитель: Alpha/);
 d.querySelector('[data-tournament-open]').click();await until(()=>d.querySelector('[data-tournament-correct]'));assert.deepEqual(errors,[]);console.log('PASS complete tournament UI with real HTTP: technical loss, correction, audit, winner, mine navigation and escaping. DOM only.');
 }finally{dom?.window.close();await app.close();fs.rmSync(temp,{recursive:true,force:true});}})().catch(e=>{console.error(e);process.exitCode=1;});
