const {JSDOM}=require('jsdom'),fs=require('node:fs'),assert=require('node:assert/strict');
(async()=>{
const dom=new JSDOM('<section id="root"></section>',{url:'https://example.test/tournaments',runScripts:'outside-only'}),w=dom.window;w.confirm=()=>true;
const root=w.document.querySelector('#root'),calls=[];let state='open',teams=[],matches=[];
const api=async(path,method,body)=>{calls.push({path,method,body});if(method==='POST'){if(path==='/api/tournaments')return {id:1};if(path.endsWith('/join'))teams=[{id:1,name:body.name,captain_id:'u'}];if(path.endsWith('/start')){state='running';matches=[{round:1,slot:0,team_a:1,team_b:2}];teams.push({id:2,name:'Opponent',captain_id:'v'});}if(path.endsWith('/results')){state='finished';matches[0]={...matches[0],score_a:body.scoreA,score_b:body.scoreB,winner:1};}return {ok:true};}
return path==='/api/tournaments'?{tournaments:[]}:{tournament:{id:1,title:'Title <img src=x>',description:'Rules',state,capacity:4,owner_id:'u'},teams,matches,myTeam:teams.find(x=>x.captain_id==='u')?.id};};
w.eval(fs.readFileSync(require('node:path').join(__dirname,'../server/public/tournaments.js'),'utf8'));const c=w.createTournaments({root,user:{id:'u'},api}),settle=()=>new Promise(r=>setTimeout(r,20));await settle();
let f=root.querySelector('[data-tournament-create]');f.elements.title.value='New cup';f.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await settle();assert.equal(w.location.search,'?id=1');assert.equal(root.querySelector('img'),null);
f=root.querySelector('[data-tournament-join]');f.elements.name.value='My team';f.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await settle();assert.match(root.textContent,/My team/);root.querySelector('[data-tournament-start]').click();await settle();
f=root.querySelector('[data-tournament-result]');f.elements.scoreA.value='2';f.elements.scoreB.value='1';f.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await settle();assert.match(root.textContent,/Победитель — My team/);assert.equal(root.querySelector('[data-tournament-result]'),null);c.destroy();dom.window.close();console.log('PASS tournament UI: create, register, start, results, winner, escaping and deep link. DOM only.');
})().catch(e=>{console.error(e);process.exit(1)});
(async()=>{
const dom=new JSDOM('<section id="root"></section>',{url:'https://example.test/tournaments?id=7',runScripts:'outside-only'}),w=dom.window;w.confirm=()=>true;
const root=w.document.querySelector('#root'),calls=[];
let data={tournament:{id:7,title:'Roster cup',description:'',state:'open',capacity:4,owner_id:'organizer'},teams:[{id:1,name:'Team',captain_id:'captain',memberCount:1,roster_required:1}],matches:[],myTeam:1,invitation:null,roster:[{user_id:'captain',handle:'captain',status:'accepted'}]};
const api=async(path,method,body)=>{if(method==='POST'){calls.push({path,body});if(path.endsWith('/invite'))data.roster.push({user_id:'player',handle:'player<img>',status:'pending'});if(path.endsWith('/remove'))data.roster=data.roster.filter(x=>x.user_id!=='player');if(path.endsWith('/accept')){data.invitation=null;data.myTeam=1;data.roster=[{user_id:'captain',handle:'captain',status:'accepted'},{user_id:'player',handle:'player',status:'accepted'}];}if(path.endsWith('/member-leave')){data.myTeam=null;data.roster=[];}return {ok:true};}return structuredClone(data);};
w.eval(fs.readFileSync(require('node:path').join(__dirname,'../server/public/tournaments.js'),'utf8'));const settle=()=>new Promise(r=>setTimeout(r,20));let controller=w.createTournaments({root,user:{id:'captain'},api});await settle();
let form=root.querySelector('[data-tournament-invite]');form.elements.handle.value='player';form.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await settle();assert.equal(calls.at(-1).path,'/api/tournaments/7/invite');assert.match(root.textContent,/ожидаем ответ/);assert.equal(root.querySelector('img'),null);
root.querySelector('[data-tournament-remove]').click();await settle();assert.equal(calls.at(-1).body.userId,'player');assert.equal(root.querySelector('[data-tournament-remove]'),null);controller.destroy();
data.myTeam=null;data.roster=[];data.invitation={id:1,name:'Team'};controller=w.createTournaments({root,user:{id:'player'},api});await settle();assert.equal(root.querySelector('[data-tournament-join]'),null);assert.equal(root.querySelector('[data-tournament-invite]'),null);
root.querySelector('[data-tournament-accept]').click();await settle();assert.equal(calls.at(-1).path,'/api/tournaments/7/accept');assert.equal(root.querySelector('[data-tournament-leave]'),null);assert.ok(root.querySelector('[data-tournament-member-leave]'));assert.equal(root.querySelector('[data-tournament-remove]'),null);
root.querySelector('[data-tournament-member-leave]').click();await settle();assert.ok(root.querySelector('[data-tournament-join]'));controller.destroy();dom.window.close();console.log('PASS roster UI: captain invitation and removal, player consent and exit, escaping and permissions. DOM only.');
})().catch(e=>{console.error(e);process.exit(1)});
