import {fail,text} from './security.mjs';import {transaction} from './database.mjs';import {unblocked,postExtras,attemptId} from './discussions.mjs';import {fold} from './players.mjs';
const topics=['champion','build','macro','roles','beginner'];
function fields(body){const title=text(body.title,'Заголовок',1,100),content=text(body.body,'Руководство',1,12000),topic=body.topic,champion=text(body.champion??'','Чемпион',0,40),gameVersion=text(body.gameVersion,'Версия игры',1,20),summary=text(body.summary??'','Краткое описание',0,240);if(!topics.includes(topic))fail(422,'Выбери тему руководства.');if(!/^\d{1,2}\.\d{1,2}(?:\.\d{1,2})?[a-z]?$/i.test(gameVersion))fail(422,'Версия: номер с точкой и необязательной буквой.');if('imageId' in body)fail(422,'Этот редактор сохраняет текст руководства.');return {title,body:content,topic,champion,gameVersion:gameVersion.toLowerCase(),summary};}
const same=(post,g,f)=>post.title===f.title&&post.body===f.body&&g.topic===f.topic&&g.champion===f.champion&&g.game_version===f.gameVersion&&g.summary===f.summary;
export function guideRoutes({db,user,path,method,body,url,send,now,clubFor,postFor,mentions}){
 if(path==='/api/guides'){
  if(method!=='GET')fail(405,'Метод не поддерживается.');const q=text(url.searchParams.get('q')||'','Поиск',0,100),champion=text(url.searchParams.get('champion')||'','Чемпион',0,40),version=text(url.searchParams.get('gameVersion')||'','Версия',0,20),topic=url.searchParams.get('topic')||'',club=url.searchParams.get('club')||'',raw=url.searchParams.get('before')||String(Number.MAX_SAFE_INTEGER);
  if(topic&&!topics.includes(topic)||!/^\d+$/.test(raw)||!Number.isSafeInteger(Number(raw)))fail(422,'Проверь фильтры и курсор.');if(club)clubFor(club,user);
  const posts=db.prepare(`SELECT p.*,u.name AS author_name,CASE WHEN u.profile_visible=1 THEN u.avatar_id ELSE NULL END AS author_avatar_id,c.name AS club_name FROM guides g JOIN posts p ON p.id=g.post_id JOIN users u ON u.id=p.author_id JOIN clubs c ON c.id=p.club_id LEFT JOIN memberships m ON m.club_id=c.id AND m.user_id=:viewer WHERE p.id<:before AND (:club='' OR c.id=:club) AND (:topic='' OR g.topic=:topic) AND (:version='' OR wr_fold(g.game_version)=:version) AND (:champion='' OR instr(wr_fold(g.champion),:champion)>0) AND (:q='' OR instr(wr_fold(p.title),:q)>0 OR instr(wr_fold(p.body),:q)>0 OR instr(wr_fold(g.summary),:q)>0) AND (m.status IS NULL OR m.status!='banned') AND (c.access='open' OR m.status='member') AND ${unblocked()} ORDER BY p.id DESC LIMIT 21`).all({viewer:user?.id||'',club,topic,version:fold(version),champion:fold(champion),q:fold(q),before:Number(raw)});
  send(200,{viewerId:user?.id||null,posts:postExtras(db,posts.slice(0,20),user,now),next:posts.length>20?posts[19].id:null});return true;
 }
 const create=path.match(/^\/api\/clubs\/([\w-]+)\/guides$/),edit=path.match(/^\/api\/posts\/(\d+)\/guide$/);if(!create&&!edit)return false;
 if(method!==(create?'POST':'PATCH'))fail(405,'Метод не поддерживается.');if(!user)fail(401,'Сначала войди в аккаунт.');
 let post;if(create)clubFor(create[1],user,true);else{const id=Number(edit[1]);if(!Number.isSafeInteger(id))fail(404,'Руководство недоступно.');post=postFor(id,user,true);if(post.author_id!==user.id)fail(403,'Изменить руководство может только автор.');if(!db.prepare('SELECT 1 FROM guides WHERE post_id=?').get(id))fail(404,'Руководство недоступно.');}
 const f=fields(body),clientId=attemptId(body);if(!clientId)fail(422,'Некорректная попытка сохранения.');if(edit&&(!Number.isSafeInteger(body.version)||body.version<1))fail(422,'Некорректная версия изменения.');
 const result=transaction(db,()=>{
  if(create){const old=db.prepare('SELECT * FROM posts WHERE club_id=? AND author_id=? AND client_id=?').get(create[1],user.id,clientId);if(old){const g=db.prepare('SELECT * FROM guides WHERE post_id=?').get(old.id);if(!g||!same(old,g,f))fail(409,'Эта попытка использована для другого текста.');return {id:old.id,replayed:true};}
   const id=Number(db.prepare('INSERT INTO posts(club_id,author_id,title,body,created_at,client_id) VALUES(?,?,?,?,?,?)').run(create[1],user.id,f.title,f.body,now(),clientId).lastInsertRowid);db.prepare('INSERT INTO guides VALUES(?,?,?,?,?)').run(id,f.topic,f.champion,f.gameVersion,f.summary);mentions(db,{post:{id,club_id:create[1],author_id:user.id},actor:user,body:f.title+'\n'+f.body,now});return {id,replayed:false};
  }
  const current=db.prepare('SELECT * FROM posts WHERE id=?').get(post.id),g=db.prepare('SELECT * FROM guides WHERE post_id=?').get(post.id);
  if(current.edit_client_id===clientId){if(!same(current,g,f))fail(409,'Эта попытка использована для другого текста.');return {id:post.id,version:current.edit_version,replayed:true};}
  if(current.edit_version!==body.version)fail(409,'Руководство изменено в другой вкладке. Твой текст остаётся здесь. Загрузи сохранённую версию.');
  if(same(current,g,f))return {id:post.id,version:current.edit_version,replayed:false};
  db.prepare('UPDATE posts SET title=?,body=?,edit_version=edit_version+1,edited_at=?,edit_client_id=? WHERE id=?').run(f.title,f.body,now(),clientId,post.id);db.prepare('UPDATE guides SET topic=?,champion=?,game_version=?,summary=? WHERE post_id=?').run(f.topic,f.champion,f.gameVersion,f.summary,post.id);return {id:post.id,version:current.edit_version+1,replayed:false};
 });send(create&&!result.replayed?201:200,result);return true;
}
