import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createApp} from '../app.mjs';
import {openDatabase} from '../database.mjs';
import {digest} from '../security.mjs';
const password='Account-security-old-123',changed='Account-security-new-456';
test('own session references, pagination, individual revoke and atomic password rotation',async t=>{
 const dir=mkdtempSync(join(tmpdir(),'wr-account-security-')),file=join(dir,'db.sqlite'),app=await createApp({databasePath:file}),origin=await app.listen();
 const db=openDatabase(file);t.after(async()=>{db.close();await app.close();rmSync(dir,{recursive:true,force:true});});
 const client=()=>({cookie:'',csrf:'',async call(path,method='GET',data,headers={}){const r=await fetch(origin+path,{method,headers:{Cookie:this.cookie,Origin:origin,'Content-Type':'application/json','X-Community-Request':'1','X-CSRF-Token':this.csrf,...headers},...(data?{body:JSON.stringify(data)}:{})});const body=await r.json();if(r.headers.has('set-cookie'))this.cookie=r.headers.get('set-cookie').split(';')[0];if(body.csrf)this.csrf=body.csrf;if(body.user)this.id=body.user.id;return {status:r.status,headers:r.headers,...body};}});
 const a=client(),b=client(),x=client(),guest=client();await a.call('/api/register','POST',{handle:'account_owner',name:'Owner',password});await b.call('/api/login','POST',{handle:'account_owner',password});await x.call('/api/register','POST',{handle:'outsider',name:'Outsider',password});
 db.prepare('INSERT INTO sessions VALUES(?,?,?,?)').run(digest('expired-session'),a.id,'expired-csrf',Date.now()-1);
 const own=await a.call('/api/sessions');assert.equal(own.sessions.length,2);assert.equal(own.sessions.filter(s=>s.current).length,1);assert.equal(own.headers.get('cache-control'),'no-store');
 const serialized=JSON.stringify(own.sessions);assert(!serialized.includes(a.cookie.slice(11)));assert(!serialized.includes(digest(a.cookie.slice(11))));assert(!serialized.includes(a.csrf));
 const other=own.sessions.find(s=>!s.current);assert.equal((await guest.call('/api/sessions')).status,401);
 assert.equal((await x.call('/api/sessions/'+other.id,'DELETE',{})).status,404);
 assert.equal((await a.call('/api/sessions/'+other.id,'DELETE',{}, {'X-CSRF-Token':'wrong'})).status,403);
 assert.equal((await a.call('/api/sessions/'+other.id,'DELETE',{})).status,200);assert.equal((await b.call('/api/me')).user,null);assert.equal((await a.call('/api/me')).user.id,a.id);
 for(let i=0;i<105;i++)db.prepare('INSERT INTO sessions VALUES(?,?,?,?)').run(digest('extra-session-'+i),a.id,'extra-csrf',Date.now()+86400000+i);
 const first=await a.call('/api/sessions'),second=await a.call('/api/sessions?after='+first.next);assert.equal(first.sessions.length,100);assert.equal(second.sessions.length,6);assert.equal(new Set([...first.sessions,...second.sessions].map(s=>s.id)).size,106);assert.equal(second.next,null);assert.equal((await a.call('/api/sessions?after=broken')).status,422);
 await b.call('/api/login','POST',{handle:'account_owner',password});const codes=await a.call('/api/recovery-codes','POST',{password});assert.equal(codes.codes.length,8);
 const club=await a.call('/api/clubs','POST',{name:'Сохранить',description:'',access:'request'});const post=await a.call('/api/clubs/'+club.id+'/posts','POST',{title:'Keep',body:'Content unchanged'});
 assert.equal((await a.call('/api/me/password','POST',{currentPassword:'Wrong-password-000',newPassword:changed})).status,401);
 assert.equal((await a.call('/api/me/password','POST',{currentPassword:password,newPassword:changed},{Origin:'https://evil.invalid'})).status,403);
 assert.equal((await a.call('/api/me/password','POST',{currentPassword:password,newPassword:changed},{'X-CSRF-Token':'wrong'})).status,403);
 const attempts=await Promise.all([a.call('/api/me/password','POST',{currentPassword:password,newPassword:changed}),a.call('/api/me/password','POST',{currentPassword:password,newPassword:'Another-new-password-789'})]);assert.deepEqual(attempts.map(r=>r.status).sort(),[200,403]);
 const winner=attempts[0].status===200?changed:'Another-new-password-789';assert.equal((await b.call('/api/me')).user,null);assert.equal((await a.call('/api/sessions')).sessions.length,1);assert.equal((await a.call('/api/recovery-codes')).remaining,0);
 assert.equal((await b.call('/api/login','POST',{handle:'account_owner',password})).status,401);assert.equal((await b.call('/api/login','POST',{handle:'account_owner',password:winner})).status,200);
 assert.equal(db.prepare('SELECT body FROM posts WHERE id=?').get(post.id).body,'Content unchanged');
 assert.equal((await guest.call('/api/recover','POST',{handle:'account_owner',code:codes.codes[0],password:'Unused-new-password-999'})).status,401);
 const current=(await a.call('/api/sessions')).sessions.find(s=>s.current);const revoke=await a.call('/api/sessions/'+current.id,'DELETE',{});assert.equal(revoke.loggedOut,true);assert(revoke.headers.get('set-cookie').includes('Max-Age=0'));assert.equal((await a.call('/api/me')).user,null);assert.equal((await b.call('/api/me')).user.id,b.id);
});
