import test from 'node:test';
import assert from 'node:assert/strict';
import {createApp} from '../app.mjs';
import {openDatabase} from '../database.mjs';
import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
const time=Date.UTC(2026,9,9,12), start=time+3600000;
async function fixture(){
 const temp=mkdtempSync(join(tmpdir(),'wr-calendar-')),databasePath=join(temp,'db'),app=await createApp({databasePath,now:()=>time}),origin=await app.listen();
 const r=await fetch(origin+'/api/register',{method:'POST',headers:{Origin:origin,'X-Community-Request':'1','Content-Type':'application/json'},body:JSON.stringify({handle:'calendar_player',name:'Player',password:'Calendar-test-123'})});assert.equal(r.status,201);const session=await r.json(),cookie=r.headers.get('set-cookie').split(';')[0],uid=session.user.id,db=openDatabase(databasePath);const close=app.close.bind(app);app.close=async()=>{db.close();await close();rmSync(temp,{recursive:true,force:true});};
 return {app,origin,cookie,uid,db,get:(query='',signed=true,method='GET')=>fetch(origin+'/api/agenda/calendar'+query,{method,body:method==='POST'?'{}':undefined,headers:signed?{Cookie:cookie,Origin:origin,'X-Community-Request':'1','X-CSRF-Token':session.csrf,'Content-Type':'application/json'}:{}})};
}
function unfold(s){return s.replace(/\r\n[ \t]/g,'');}
function event(f,id,options={}){f.db.prepare("INSERT INTO game_events(id,owner_id,client_id,signature,title,description,mode,region,language,timezone,starts_at,ends_at,created_at,cancelled) VALUES(?,?,?,'s',?,'','ranked','EU','ru','UTC',?,?,?,?)").run(id,options.owner||f.uid,'calendar-'+id,options.title||'Игра',options.start??start,options.end??start+3600000,time,options.cancelled||0);}
test('calendar HTTP export has UTC times, stable UID, exact links, alarm and safe UTF-8 folded text',async()=>{const f=await fixture();try{event(f,1,{title:'Игра, лес; \\ '+ 'Привет😀'.repeat(25)+'\r\nBEGIN:VEVENT\nATTENDEE:evil'});let r=await f.get('?key=event:1');assert.equal(r.status,200);assert.match(r.headers.get('content-type'),/^text\/calendar/);assert.match(r.headers.get('content-disposition'),/attachment.*\.ics/);assert.equal(r.headers.get('cache-control'),'no-store');let text=await r.text(),s=unfold(text);assert.equal((s.match(/^BEGIN:VEVENT$/gm)||[]).length,1);assert.match(s,/DTSTART:20261009T130000Z/);assert.match(s,/DTEND:20261009T140000Z/);assert.match(s,/TRIGGER:-PT30M/);assert.ok(s.includes('URL:'+f.origin+'/events?id=1'));assert.ok(s.includes('Игра\\, лес\\; \\\\ '));assert.ok(s.includes('\\nBEGIN:VEVENT\\nATTENDEE:evil'));assert.ok(!text.includes('�'));for(const line of text.split('\r\n'))assert.ok(Buffer.byteLength(line)<=75);const uid=s.match(/^UID:(.+)\r?$/m)[1];f.db.prepare('UPDATE game_events SET starts_at=?,ends_at=? WHERE id=1').run(start+7200000,start+10800000);s=unfold(await (await f.get('?key=event:1')).text());assert.ok(s.includes('UID:'+uid));assert.match(s,/DTSTART:20261009T150000Z/);}finally{await f.app.close();}});
test('calendar export checks live membership, blocks, cancellation, finished and undated matches',async()=>{const f=await fixture();try{event(f,1);assert.equal((await f.get('',false)).status,401);assert.equal((await f.get('?key=event:1&status=all')).status,422);assert.equal((await f.get('?key=event:1',true,'POST')).status,405);assert.equal((await f.get('?key=garbage')).status,422);f.db.exec("INSERT INTO users(id,handle,name,password,created_at) VALUES('other','calendar_other','Other','hash',0)");event(f,2,{owner:'other'});assert.equal((await f.get('?key=event:2')).status,404);f.db.prepare('INSERT INTO event_slots VALUES(2,\'mid\',?)').run(f.uid);assert.equal((await f.get('?key=event:2')).status,200);f.db.prepare('INSERT INTO blocks VALUES(?,?)').run('other',f.uid);assert.equal((await f.get('?key=event:2')).status,404);f.db.prepare('DELETE FROM blocks').run();f.db.prepare('DELETE FROM event_slots WHERE event_id=2').run();assert.equal((await f.get('?key=event:2')).status,404);f.db.prepare('UPDATE game_events SET cancelled=1 WHERE id=1').run();assert.equal((await f.get('?key=event:1')).status,404);assert.equal((await f.get()).status,422);
 f.db.prepare("INSERT INTO tournaments(id,owner_id,title,description,capacity,client_id,signature,created_at,state) VALUES(1,?,'Cup','',4,'calendar-cup','s',0,'running')").run(f.uid);f.db.prepare("INSERT INTO tournament_teams(id,tournament_id,captain_id,name) VALUES(1,1,?,'Alpha'),(2,1,'other','Beta')").run(f.uid);f.db.prepare('INSERT INTO tournament_matches(tournament_id,round,slot,team_a,team_b,starts_at) VALUES(1,1,0,1,2,?),(1,1,1,1,2,NULL),(1,2,0,1,2,?)').run(start,time-1000);let s=unfold(await (await f.get('?type=tournaments')).text());assert.equal((s.match(/^BEGIN:VEVENT$/gm)||[]).length,1);assert.ok(s.includes('URL:'+f.origin+'/tournaments?id=1&round=1&slot=0'));assert.ok(s.includes('Alpha — Beta'));assert.ok(!s.includes('DTEND:'));assert.equal((await f.get('?key=match:1:1:1')).status,422);assert.equal((await f.get('?key=match:1:2:0')).status,422);f.db.prepare('UPDATE tournament_matches SET winner=1 WHERE round=1 AND slot=0').run();assert.equal((await f.get('?key=match:1:1:0')).status,404);
 }finally{await f.app.close();}});
test('calendar export includes every future page and respects type without accepting stale cursors',async()=>{const f=await fixture();try{for(let i=1;i<=65;i++)event(f,i);event(f,66,{cancelled:1});event(f,67,{start:time-7200000,end:time-3600000});const r=await f.get('?type=events'),s=unfold(await r.text());assert.equal(r.status,200);assert.equal((s.match(/^BEGIN:VEVENT$/gm)||[]).length,65);assert.equal(new Set([...s.matchAll(/^UID:(.+)$/gm)].map(x=>x[1])).size,65);assert.equal((await f.get('?cursor=stale')).status,422);assert.equal((await f.get('?type=bad')).status,422);}finally{await f.app.close();}});
