import test from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,rmSync,readFileSync,copyFileSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {DatabaseSync} from 'node:sqlite';import sharp from 'sharp';import {openDatabase} from '../database.mjs';import {createApp} from '../app.mjs';
test('draft migration14→15 preserves posts, accounts and cold copy; repeatable',()=>{const dir=mkdtempSync(join(tmpdir(),'wr-draft-schema-'));try{const p=join(dir,'db');let d=new DatabaseSync(p);d.exec(readFileSync(new URL('./fixtures/schema-v14.sql',import.meta.url),'utf8'));d.exec("INSERT INTO users(id,handle,name,password,created_at) VALUES('u','keep','Keep','unchanged',1);INSERT INTO clubs(id,owner_id,name,description,access,created_at) VALUES('c','u','Keep','','request',1);INSERT INTO memberships VALUES('c','u','member');INSERT INTO posts(club_id,author_id,title,body,created_at) VALUES('c','u','Title','Keep body',1)");d.close();copyFileSync(p,join(dir,'backup'));for(let i=0;i<2;i++){d=openDatabase(p);assert.equal(d.prepare('PRAGMA user_version').get().user_version,26);assert.equal(d.prepare('SELECT body FROM posts').get().body,'Keep body');assert.equal(d.prepare('SELECT password FROM users').get().password,'unchanged');assert.equal(d.prepare('PRAGMA integrity_check').get().integrity_check,'ok');assert.deepEqual(d.prepare('PRAGMA foreign_key_check').all(),[]);d.close();}d=new DatabaseSync(join(dir,'backup'),{readOnly:true});assert.equal(d.prepare('PRAGMA user_version').get().user_version,14);d.close();}finally{rmSync(dir,{recursive:true,force:true});}});
test('private drafts: CAS, retry, image scope, publish transfer, membership and restart',async t=>{
 const dir=mkdtempSync(join(tmpdir(),'wr-drafts-')),databasePath=join(dir,'db');let app=await createApp({databasePath}),origin=await app.listen();t.after(async()=>{await app.close();rmSync(dir,{recursive:true,force:true});});
 function client(){return {cookie:'',csrf:'',async req(path,method='GET',body){const headers={Cookie:this.cookie};if(method!=='GET')Object.assign(headers,{Origin:origin,'Content-Type':'application/json','X-Community-Request':'1','X-CSRF-Token':this.csrf});const r=await fetch(origin+path,{method,headers,body:body===undefined?undefined:JSON.stringify(body)}),d=r.headers.get('content-type')?.includes('application/json')?await r.json():{};if(r.headers.has('set-cookie'))this.cookie=r.headers.get('set-cookie').split(';')[0];if(d.csrf)this.csrf=d.csrf;if(d.user)this.id=d.user.id;return {...d,status:r.status};},async image(){const png=await sharp({create:{width:20,height:10,channels:3,background:'blue'}}).png().toBuffer();const r=await fetch(origin+'/api/media',{method:'POST',headers:{Cookie:this.cookie,Origin:origin,'Content-Type':'image/png','X-Community-Request':'1','X-CSRF-Token':this.csrf,'X-Upload-ID':crypto.randomUUID()},body:png});assert.equal(r.status,201);return (await r.json()).image.id;}};}
 const a=client(),b=client(),c=client(),guest=client();for(const [u,h]of[[a,'draft_owner'],[b,'draft_writer'],[c,'draft_other']])await u.req('/api/register','POST',{handle:h,name:h,password:'Draft-test-only-123'});
 const club=await a.req('/api/clubs','POST',{name:'Private club',description:'',access:'request'}),root='/api/clubs/'+club.id,path=root+'/draft';for(const u of[b,c]){await u.req(root+'/join','POST',{});await a.req(root+'/decision','POST',{userId:u.id,decision:'approve'});}
 assert.equal((await guest.req(path)).status,401);const image=await b.image(),input={title:'Private <img src=x>',body:'Draft only',imageId:image,version:0};const saved=await b.req(path,'PUT',input);assert.equal(saved.status,200);assert.equal(saved.draft.version,1);assert.equal((await b.req(path,'PUT',input)).draft.version,1);assert.equal((await a.req(path)).draft,null);assert.equal((await c.req('/api/drafts')).drafts.length,0);assert.equal((await c.req('/api/media/'+image)).status,404);assert.equal((await a.req('/api/media/'+image)).status,404);assert.equal((await b.req('/api/media/'+image)).status,200);assert.equal((await b.req('/api/me','PATCH',{avatarId:image})).status,409);assert.equal((await b.req('/api/media/'+image,'DELETE',{})).status,409);assert.equal((await a.req(root+'/posts')).posts.length,0);
 const conflict=await Promise.all([b.req(path,'PUT',{...input,title:'First',version:1}),b.req(path,'PUT',{...input,title:'Second',version:1})]);assert.deepEqual(conflict.map(r=>r.status).sort(),[200,409]);let draft=(await b.req(path)).draft;assert.equal(draft.version,2);await app.close();app=await createApp({databasePath});origin=await app.listen();assert.equal((await b.req(path)).draft.version,2);
 const payload={version:2,clientId:'draft-publish-stable-001'},results=await Promise.all([b.req(path+'/publish','POST',payload),b.req(path+'/publish','POST',payload)]);assert.deepEqual(results.map(r=>r.status).sort(),[200,201]);const postId=results[0].id;assert.equal((await b.req(path)).draft,null);assert.equal((await a.req(root+'/posts')).posts.length,1);assert.equal((await a.req('/api/media/'+image)).status,200);assert.equal((await b.req('/api/media/'+image)).status,200);
 const next=await b.req(path,'PUT',{title:'New draft',body:'Keep this',version:0});assert.equal(next.draft.version,1);assert.equal((await b.req(path+'/publish','POST',payload)).status,409);assert.equal((await b.req(path)).draft.title,'New draft');assert.equal((await b.req(path,'DELETE',{version:0})).status,409);assert.equal((await b.req(path,'DELETE',{version:1})).status,200);assert.equal((await b.req(path,'DELETE',{version:1})).status,200);
 const image2=await b.image();await b.req(path,'PUT',{title:'Image draft',body:'',imageId:image2,version:0});assert.equal((await b.req(path+'/publish','POST',{version:1,clientId:'draft-empty-stable-001'})).status,422);await b.req(path,'PUT',{title:'Image removed',body:'Text',imageId:null,version:1});assert.equal((await b.req('/api/media/'+image2)).status,404);
 const image3=await b.image();await b.req(path,'PUT',{title:'Leave deletes draft',body:'Text',imageId:image3,version:2});await b.req(root+'/leave','POST',{});assert.equal((await b.req(path)).status,403);assert.equal((await b.req('/api/drafts')).drafts.length,0);assert.equal((await b.req('/api/media/'+image3)).status,404);assert.equal((await b.req('/api/media/'+image)).status,403);assert.equal((await a.req('/api/posts/'+postId)).post.image_id,image);
 const image4=await c.image();await c.req(path,'PUT',{title:'Banned draft',body:'Text',imageId:image4,version:0});await a.req(root+'/ban','POST',{userId:c.id});assert.equal((await c.req(path)).status,403);assert.equal((await c.req('/api/media/'+image4)).status,403);assert.equal((await c.req('/api/drafts')).drafts.length,0);assert.equal((await c.req(path+'/publish','POST',{version:1,clientId:'draft-ban-stable-001'})).status,403);
 const d=openDatabase(databasePath);assert.deepEqual(d.prepare('PRAGMA foreign_key_check').all(),[]);d.close();
});
