import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,readFileSync,rmSync,copyFileSync} from 'node:fs';
import {tmpdir} from 'node:os';import {join} from 'node:path';import {DatabaseSync} from 'node:sqlite';
import {createApp} from '../app.mjs';import {openDatabase} from '../database.mjs';
test('schema13→14 preserves existing content, cold backup and reopens',()=>{
 const dir=mkdtempSync(join(tmpdir(),'wr-events-schema-'));try{const path=join(dir,'db');let d=new DatabaseSync(path);d.exec(readFileSync(new URL('./fixtures/schema-v13.sql',import.meta.url),'utf8'));d.exec("INSERT INTO users(id,handle,name,password,created_at) VALUES('a','keep','Keep','unchanged',1);INSERT INTO clubs(id,owner_id,name,description,access,created_at,rules) VALUES('c','a','Keep','D','request',1,'Rule');INSERT INTO memberships VALUES('c','a','member');INSERT INTO posts(club_id,author_id,title,body,created_at) VALUES('c','a','T','Keep body',1)");d.close();copyFileSync(path,join(dir,'backup'));for(let i=0;i<2;i++){d=openDatabase(path);assert.equal(d.prepare('PRAGMA user_version').get().user_version,22);assert.equal(d.prepare('SELECT body FROM posts').get().body,'Keep body');assert.equal(d.prepare('SELECT rules FROM clubs').get().rules,'Rule');assert.equal(d.prepare('PRAGMA integrity_check').get().integrity_check,'ok');assert.deepEqual(d.prepare('PRAGMA foreign_key_check').all(),[]);d.close();}d=new DatabaseSync(join(dir,'backup'),{readOnly:true});assert.equal(d.prepare('PRAGMA user_version').get().user_version,13);d.close();}finally{rmSync(dir,{recursive:true,force:true});}
});
test('events: competing roles, private chat, reminder lifetime, retries, restart and cancellation',async t=>{
 const dir=mkdtempSync(join(tmpdir(),'wr-events-')),databasePath=join(dir,'db');let clock=Date.now(),app=await createApp({databasePath,now:()=>clock}),origin=await app.listen();t.after(async()=>{await app.close();rmSync(dir,{recursive:true,force:true});});
 function client(){return {cookie:'',csrf:'',async req(path,method='GET',body){const headers={Cookie:this.cookie};if(method!=='GET')Object.assign(headers,{Origin:origin,'Content-Type':'application/json','X-Community-Request':'1','X-CSRF-Token':this.csrf});const r=await fetch(origin+path,{method,headers,body:body===undefined?undefined:JSON.stringify(body)}),d=await r.json();if(r.headers.has('set-cookie'))this.cookie=r.headers.get('set-cookie').split(';')[0];if(d.csrf)this.csrf=d.csrf;if(d.user)this.id=d.user.id;return {...d,status:r.status};}};}
 const a=client(),b=client(),c=client(),guest=client();for(const [u,handle]of[[a,'events_owner'],[b,'events_b'],[c,'events_c']])assert.equal((await u.req('/api/register','POST',{handle,name:handle,password:'Events-local-only-123'})).status,201);
 const input={clientId:'event-create-stable-001',title:'Вечерний ранкед',description:'Test <img src=x>',mode:'ranked',region:'EU',language:'ru',timezone:'Europe/Moscow',startsAt:clock+3600000,durationHours:2,roles:['mid','jungle'],ownerRole:'mid'};
 assert.equal((await guest.req('/api/events')).status,401);assert.equal((await a.req('/api/events','POST',{...input,timezone:'invalid'})).status,422);assert.equal((await a.req('/api/events','POST',{...input,roles:['mid','mid']})).status,422);
 const results=await Promise.all([a.req('/api/events','POST',input),a.req('/api/events','POST',input)]);assert.deepEqual(results.map(r=>r.status).sort(),[200,201]);const id=results[0].id,path='/api/events/'+id;
 assert.equal((await a.req('/api/events','POST',{...input,title:'Changed'})).status,409);assert.equal((await b.req(path)).members.length,0);assert.equal((await b.req(path+'/messages')).status,403);assert.equal((await b.req('/api/events?role=jungle')).events.length,1);
 const joins=await Promise.all([b.req(path+'/join','POST',{role:'jungle'}),c.req(path+'/join','POST',{role:'jungle'})]);assert.deepEqual(joins.map(r=>r.status).sort(),[200,409]);const win=joins[0].status===200?b:c,lose=win===b?c:b;
 assert.equal((await win.req(path+'/join','POST',{role:'jungle'})).status,200);assert.equal((await a.req(path)).event.state,'full');assert.equal((await lose.req('/api/events?role=jungle')).events.length,0);assert.equal((await win.req(path)).members.length,2);
 const msg={clientId:'event-message-stable-001',body:'Приватный текст'};assert.equal((await win.req(path+'/messages','POST',msg)).status,201);assert.equal((await win.req(path+'/messages','POST',msg)).status,200);assert.equal((await win.req(path+'/messages','POST',{...msg,body:'Changed'})).status,409);assert.equal((await lose.req(path+'/messages')).status,403);
 clock=input.startsAt-1800000;for(let i=0;i<2;i++)assert.equal((await win.req('/api/events/notifications')).notifications.filter(n=>n.kind==='reminder').length,1);
 let d=openDatabase(databasePath);assert.equal(d.prepare("SELECT count(*) n FROM event_notifications WHERE kind='joined'").get().n,1);d.close();
 await app.close();app=await createApp({databasePath,now:()=>clock});origin=await app.listen();assert.equal((await win.req(path+'/messages')).messages[0].body,msg.body);
 assert.equal((await lose.req(path+'/remove','POST',{userId:win.id})).status,403);assert.equal((await a.req(path+'/remove','POST',{userId:win.id})).status,200);assert.equal((await a.req(path+'/remove','POST',{userId:win.id})).status,200);assert.equal((await win.req(path+'/messages')).status,403);assert.equal((await win.req(path+'/join','POST',{role:'jungle'})).status,403);assert.equal((await win.req('/api/events/notifications')).notifications.some(n=>n.kind==='reminder'),false);
 assert.equal((await lose.req(path+'/join','POST',{role:'jungle'})).status,200);assert.equal((await lose.req(path+'/leave','POST',{})).status,200);assert.equal((await lose.req(path+'/messages')).status,403);assert.equal((await lose.req(path+'/join','POST',{role:'jungle'})).status,200);
 await a.req('/api/blocks','POST',{userId:lose.id});assert.equal((await lose.req(path)).status,404);assert.equal((await lose.req(path+'/messages')).status,404);assert.equal((await lose.req('/api/events?mine=1')).events.length,0);await a.req('/api/blocks','DELETE',{userId:lose.id});
 assert.equal((await a.req(path+'/leave','POST',{})).status,409);assert.equal((await lose.req(path+'/cancel','POST',{})).status,403);await a.req(path+'/cancel','POST',{});await a.req(path+'/cancel','POST',{});assert.equal((await lose.req(path+'/messages')).canSend,false);assert.equal((await lose.req(path+'/messages','POST',{...msg,clientId:'event-new-message-001'})).status,409);assert.equal((await lose.req('/api/events/notifications')).notifications.filter(n=>n.kind==='cancelled').length,1);assert.equal((await lose.req('/api/events/notifications')).notifications.some(n=>n.kind==='reminder'),false);
 const second=await a.req('/api/events','POST',{...input,clientId:'event-create-stable-002',startsAt:clock+600000});clock+=600000;assert.equal((await b.req('/api/events/'+second.id+'/join','POST',{role:'jungle'})).status,409);
});
