import test from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,rmSync,readFileSync,copyFileSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {DatabaseSync} from 'node:sqlite';import sharp from 'sharp';import {openDatabase} from '../database.mjs';import {createApp} from '../app.mjs';
test('schema17→18 preserves polls, drafts and edit metadata; cold copy and repeat',()=>{const dir=mkdtempSync(join(tmpdir(),'wr-guide-schema-'));try{const p=join(dir,'db');let d=new DatabaseSync(p);d.exec(readFileSync(new URL('./fixtures/schema-v17.sql',import.meta.url),'utf8'));d.exec("INSERT INTO users(id,handle,name,password,created_at) VALUES('u','keep','Keep','unchanged',1);INSERT INTO clubs(id,owner_id,name,description,access,created_at) VALUES('c','u','Keep','','request',1);INSERT INTO memberships VALUES('c','u','member');INSERT INTO posts(club_id,author_id,title,body,created_at,edit_version) VALUES('c','u','Title','Keep',1,3);INSERT INTO polls VALUES(1,'c',9999999999999,1);INSERT INTO poll_options VALUES(1,0,'First');INSERT INTO poll_options VALUES(1,1,'Second');INSERT INTO poll_votes VALUES(1,'u','c',0,1);INSERT INTO post_drafts VALUES('c','u','Draft','Private',NULL,2,1)");d.close();copyFileSync(p,join(dir,'backup'));for(let i=0;i<2;i++){d=openDatabase(p);assert.equal(d.prepare('PRAGMA user_version').get().user_version,26);assert.equal(d.prepare('SELECT edit_version FROM posts').get().edit_version,3);assert.equal(d.prepare('SELECT count(*) n FROM poll_votes').get().n,1);assert.equal(d.prepare('SELECT body FROM post_drafts').get().body,'Private');assert.equal(d.prepare('PRAGMA integrity_check').get().integrity_check,'ok');assert.deepEqual(d.prepare('PRAGMA foreign_key_check').all(),[]);d.close();}d=new DatabaseSync(join(dir,'backup'),{readOnly:true});assert.equal(d.prepare('PRAGMA user_version').get().user_version,17);d.close();}finally{rmSync(dir,{recursive:true,force:true});}});
test('guides: access, long Unicode payload, search filters/pagination, CAS/retry, restart and revocation',async t=>{
const dir=mkdtempSync(join(tmpdir(),'wr-guides-')),databasePath=join(dir,'db');let app=await createApp({databasePath}),origin=await app.listen();t.after(async()=>{await app.close();rmSync(dir,{recursive:true,force:true});});
 function client(){return {cookie:'',csrf:'',async req(path,method='GET',body){const headers={Cookie:this.cookie};if(method!=='GET')Object.assign(headers,{Origin:origin,'Content-Type':'application/json','X-Community-Request':'1','X-CSRF-Token':this.csrf});const r=await fetch(origin+path,{method,headers,body:body===undefined?undefined:JSON.stringify(body)}),d=r.headers.get('content-type')?.includes('application/json')?await r.json():{};if(r.headers.has('set-cookie'))this.cookie=r.headers.get('set-cookie').split(';')[0];if(d.csrf)this.csrf=d.csrf;if(d.user)this.id=d.user.id;return {...d,status:r.status};},async image(){const png=await sharp({create:{width:20,height:10,channels:3,background:'blue'}}).png().toBuffer();const r=await fetch(origin+'/api/media',{method:'POST',headers:{Cookie:this.cookie,Origin:origin,'Content-Type':'image/png','X-Community-Request':'1','X-CSRF-Token':this.csrf,'X-Upload-ID':crypto.randomUUID()},body:png});assert.equal(r.status,201);return (await r.json()).image.id;}};}
const a=client(),b=client(),c=client(),guest=client();for(const [u,h]of[[a,'guide_host'],[b,'guide_writer'],[c,'guide_other']])await u.req('/api/register','POST',{handle:h,name:h,password:'Guide-test-only-123'});
const club=await a.req('/api/clubs','POST',{name:'Private guides',description:'',access:'request'}),root='/api/clubs/'+club.id;await b.req(root+'/join','POST',{});await a.req(root+'/decision','POST',{userId:b.id,decision:'approve'});
const input={title:'Гайд <img src=x>',body:'Совет '.repeat(1800),topic:'champion',champion:'Ренгар',gameVersion:'7.3A',summary:'Авторский опыт',clientId:'guide-create-stable-001'};assert.equal((await guest.req(root+'/guides','POST',input)).status,401);assert.equal((await c.req(root+'/guides','POST',input)).status,403);assert.equal((await b.req(root+'/guides','POST',{...input,gameVersion:'latest'})).status,422);assert.equal((await b.req(root+'/guides','POST',{...input,body:'я'.repeat(12001)})).status,422);
const created=await Promise.all([b.req(root+'/guides','POST',input),b.req(root+'/guides','POST',input)]);assert.deepEqual(created.map(x=>x.status).sort(),[200,201]);const id=created[0].id,path='/api/posts/'+id+'/guide';assert.equal((await b.req(root+'/guides','POST',{...input,topic:'macro'})).status,409);assert.equal((await a.req('/api/guides?champion=РЕНГ&topic=champion&gameVersion=7.3a')).posts.length,1);assert.equal((await guest.req('/api/guides')).posts.length,0);assert.equal((await c.req('/api/guides')).posts.length,0);assert.equal((await c.req('/api/guides?club='+club.id)).status,403);assert.equal((await a.req('/api/guides?topic=unknown')).status,422);assert.equal((await a.req('/api/guides?gameVersion=7.3')).posts.length,0);assert.equal((await a.req('/api/guides?q=авторский')).posts.length,1);
const edit={...input,title:'Обновлённый гайд',gameVersion:'7.4',topic:'macro',version:1,clientId:'guide-edit-stable-001'};assert.equal((await a.req(path,'PATCH',edit)).status,403);assert.equal((await b.req('/api/posts/'+id,'PATCH',{...edit,body:'Short'})).status,409);const pair=await Promise.all([b.req(path,'PATCH',edit),b.req(path,'PATCH',{...edit,clientId:'guide-edit-stable-002'})]);assert.deepEqual(pair.map(x=>x.status).sort(),[200,409]);const accepted=pair[0].status===200?edit:{...edit,clientId:'guide-edit-stable-002'};assert.equal((await b.req(path,'PATCH',accepted)).version,2);assert.equal((await b.req(path,'PATCH',{...accepted,topic:'build'})).status,409);assert.equal((await a.req('/api/guides?gameVersion=7.4&topic=macro')).posts.length,1);assert.equal((await a.req('/api/posts/'+id)).post.guide.game_version,'7.4');
const d=openDatabase(databasePath);for(let i=0;i<23;i++){const n=Number(d.prepare('INSERT INTO posts(club_id,author_id,title,body,created_at) VALUES(?,?,?,?,?)').run(club.id,b.id,'Пагинация '+i,'Text',1).lastInsertRowid);d.prepare('INSERT INTO guides VALUES(?,?,?,?,?)').run(n,'roles','','7.3','');}d.close();const first=await a.req('/api/guides?topic=roles'),second=await a.req('/api/guides?topic=roles&before='+first.next);assert.equal(first.posts.length,20);assert.equal(second.posts.length,3);assert.equal(new Set([...first.posts,...second.posts].map(p=>p.id)).size,23);
await a.req('/api/blocks','POST',{userId:b.id});assert.equal((await a.req('/api/guides')).posts.length,0);await a.req('/api/blocks','DELETE',{userId:b.id});await app.close();app=await createApp({databasePath});origin=await app.listen();assert.equal((await b.req('/api/posts/'+id)).post.edit_version,2);await b.req(root+'/leave','POST',{});assert.equal((await b.req(path,'PATCH',{...edit,version:2})).status,403);assert.equal((await b.req('/api/guides')).posts.length,0);
const pub=await a.req('/api/clubs','POST',{name:'Public guides',description:'',access:'open'}),p=await a.req('/api/clubs/'+pub.id+'/guides','POST',{...input,body:'Public',clientId:'guide-public-stable-001'});assert.equal((await guest.req('/api/guides')).posts.length,1);await a.req('/api/posts/'+p.id,'DELETE',{});const check=openDatabase(databasePath);assert.equal(check.prepare('SELECT count(*) n FROM guides WHERE post_id=?').get(p.id).n,0);assert.deepEqual(check.prepare('PRAGMA foreign_key_check').all(),[]);check.close();
});
