import test from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {createApp} from '../app.mjs';import {openDatabase} from '../database.mjs';
test('personal home filters before LIMIT, protects private data and follows current membership',async t=>{
 const dir=mkdtempSync(join(tmpdir(),'wr-home-')),databasePath=join(dir,'db');const clock=Date.now(),app=await createApp({databasePath,now:()=>clock}),origin=await app.listen();t.after(async()=>{await app.close();rmSync(dir,{recursive:true,force:true});});
 function client(){return {cookie:'',csrf:'',async req(path,method='GET',body){const headers={Cookie:this.cookie};if(method!=='GET')Object.assign(headers,{Origin:origin,'Content-Type':'application/json','X-Community-Request':'1','X-CSRF-Token':this.csrf});const r=await fetch(origin+path,{method,headers,body:body===undefined?undefined:JSON.stringify(body)}),d=await r.json();if(r.headers.has('set-cookie'))this.cookie=r.headers.get('set-cookie').split(';')[0];if(d.csrf)this.csrf=d.csrf;if(d.user)this.id=d.user.id;return {...d,status:r.status};}};}
 const a=client(),b=client(),c=client(),guest=client();for(const [u,handle]of[[a,'home_player'],[b,'home_owner'],[c,'home_blocked']])await u.req('/api/register','POST',{handle,name:handle,password:'Home-test-only-123'});
 assert.equal((await guest.req('/api/home')).status,401);assert.equal((await a.req('/api/home','POST',{})).status,405);
 await a.req('/api/me','PATCH',{profileVisible:false,gameProfile:{riotId:'Private#123',riotVisible:false,region:'EU',language:'Русский',roles:['jungle'],rank:'Diamond',microphone:'no'}});
 let db=openDatabase(databasePath);for(let i=0;i<9;i++){db.prepare("INSERT INTO clubs(id,owner_id,name,description,access,created_at) VALUES(?,?,?,'','request',?)").run('home-club-'+i,b.id,'Club '+i,i);db.prepare('INSERT INTO memberships VALUES(?,?,?)').run('home-club-'+i,a.id,i<7?'member':i===7?'pending':'banned');}
 function group(n,{owner=b.id,role='jungle',region='eu',language='русский',rank='Diamond',voice='optional',closed=0,expires=clock+3600000,full=false,status=null}={}){const id=Number(db.prepare("INSERT INTO lfg_groups(owner_id,client_id,create_signature,title,mode,region,language,role,rank,voice,description,capacity,starts_at,expires_at,created_at,closed) VALUES(?,?,'signature',?,'ranked',?,?,?,?,?,'secret-not-a-chat',2,?,?,?,?)").run(owner,'home-fixture-'+n,n,region,language,role,rank,voice,clock,expires,clock,closed).lastInsertRowid);db.prepare("INSERT INTO lfg_members VALUES(?,?,'accepted')").run(id,owner);if(full)db.prepare("INSERT INTO lfg_members VALUES(?,?,'accepted')").run(id,c.id);if(status)db.prepare('INSERT INTO lfg_members VALUES(?,?,?)').run(id,a.id,status);return id;}
 const match=group('Relevant'),pending=group('Pending',{status:'pending'}),mine=group('Accepted',{status:'accepted'});for(let i=0;i<25;i++)group('Wrong region '+i,{region:'NA'});group('Wrong role',{role:'support'});group('Wrong rank',{rank:'Gold'});group('Wrong language',{language:'de'});group('Voice required',{voice:'required'});group('Closed',{closed:1});group('Expired',{expires:clock-1});group('Full',{full:true});group('Rejected',{status:'rejected'});group('Blocked',{owner:c.id});
 function event(n,start,{cancelled=0,member=true,owner=b.id}={}){const id=Number(db.prepare("INSERT INTO game_events(owner_id,client_id,signature,title,description,mode,region,language,timezone,starts_at,ends_at,created_at,cancelled) VALUES(?,?,'signature',?,'Private description','ranked','EU','ru','UTC',?,?,?,?)").run(owner,'home-event-'+n,n,start,start+3600000,clock,cancelled).lastInsertRowid);db.prepare('INSERT INTO event_slots VALUES(?,?,?)').run(id,'mid',owner);db.prepare('INSERT INTO event_slots VALUES(?,?,?)').run(id,'jungle',member?a.id:null);return id;}
 const later=event('Later',clock+2400000),soon=event('Soon',clock+600000);event('Cancelled',clock+300000,{cancelled:1});event('Ended',clock-7200000);event('Not a member',clock+300000,{member:false});event('Blocked event',clock+300000,{owner:c.id});db.close();
 await a.req('/api/blocks','POST',{userId:c.id});const home=await a.req('/api/home');assert.equal(home.status,200);assert.equal(home.viewerId,a.id);assert.equal(home.clubCount,7);assert.equal(home.myClubs.length,6);assert(home.myClubs.every(c=>!['home-club-7','home-club-8'].includes(c.id)));assert.deepEqual(home.events.map(e=>e.id),[soon,later]);assert.deepEqual(home.groups.map(g=>g.id),[match]);assert.deepEqual(home.myGroups.map(g=>g.id).sort(),[pending,mine].sort());assert.equal(home.preferences.region,'EU');assert(!JSON.stringify(home).includes('Private#123'));assert(!JSON.stringify(home).includes('Private description'));assert(!JSON.stringify(home).includes('create_signature'));
 db=openDatabase(databasePath);db.prepare('DELETE FROM memberships WHERE club_id=? AND user_id=?').run('home-club-6',a.id);db.prepare('UPDATE event_slots SET user_id=NULL WHERE event_id=? AND user_id=?').run(soon,a.id);db.prepare("UPDATE lfg_members SET status='rejected' WHERE group_id=? AND user_id=?").run(mine,a.id);db.close();const next=await a.req('/api/home');assert.equal(next.clubCount,6);assert(!next.myClubs.some(c=>c.id==='home-club-6'));assert(!next.events.some(e=>e.id===soon));assert(!next.myGroups.some(g=>g.id===mine));assert(!next.groups.some(g=>g.id===mine));
 const fresh=await b.req('/api/home');assert.equal(fresh.viewerId,b.id);assert.deepEqual(fresh.preferences,{});assert.equal(fresh.myClubs.length,0);assert(fresh.events.every(e=>e.myRole==='mid'));
});
