import test from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,rmSync,readFileSync,copyFileSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {DatabaseSync} from 'node:sqlite';import sharp from 'sharp';import {openDatabase} from '../database.mjs';import {createApp} from '../app.mjs';
test('schema16→17 keeps posts, drafts, edited metadata and cold backup; repeatable',()=>{const dir=mkdtempSync(join(tmpdir(),'wr-poll-schema-'));try{const p=join(dir,'db');let d=new DatabaseSync(p);d.exec(readFileSync(new URL('./fixtures/schema-v16.sql',import.meta.url),'utf8'));d.exec("INSERT INTO users(id,handle,name,password,created_at) VALUES('u','keep','Keep','unchanged',1);INSERT INTO clubs(id,owner_id,name,description,access,created_at) VALUES('c','u','Keep','','request',1);INSERT INTO memberships VALUES('c','u','member');INSERT INTO posts(club_id,author_id,title,body,created_at,edit_version,edited_at) VALUES('c','u','Title','Keep',1,3,2);INSERT INTO post_drafts VALUES('c','u','Draft','Private',NULL,2,1)");d.close();copyFileSync(p,join(dir,'backup'));for(let i=0;i<2;i++){d=openDatabase(p);assert.equal(d.prepare('PRAGMA user_version').get().user_version,29);assert.equal(d.prepare('SELECT edit_version FROM posts').get().edit_version,3);assert.equal(d.prepare('SELECT body FROM post_drafts').get().body,'Private');assert.equal(d.prepare('PRAGMA integrity_check').get().integrity_check,'ok');assert.deepEqual(d.prepare('PRAGMA foreign_key_check').all(),[]);d.close();}d=new DatabaseSync(join(dir,'backup'),{readOnly:true});assert.equal(d.prepare('PRAGMA user_version').get().user_version,16);d.close();}finally{rmSync(dir,{recursive:true,force:true});}});
test('poll access, creation retry, single immutable vote, deadlines, counts, restart and cascades',async t=>{
 const dir=mkdtempSync(join(tmpdir(),'wr-polls-')),databasePath=join(dir,'db');let clock=Date.now(),app=await createApp({databasePath,now:()=>clock}),origin=await app.listen();t.after(async()=>{await app.close();rmSync(dir,{recursive:true,force:true});});
 function client(){return {cookie:'',csrf:'',async req(path,method='GET',body){const headers={Cookie:this.cookie};if(method!=='GET')Object.assign(headers,{Origin:origin,'Content-Type':'application/json','X-Community-Request':'1','X-CSRF-Token':this.csrf});const r=await fetch(origin+path,{method,headers,body:body===undefined?undefined:JSON.stringify(body)}),d=r.headers.get('content-type')?.includes('application/json')?await r.json():{};if(r.headers.has('set-cookie'))this.cookie=r.headers.get('set-cookie').split(';')[0];if(d.csrf)this.csrf=d.csrf;if(d.user)this.id=d.user.id;return {...d,status:r.status};},async image(){const png=await sharp({create:{width:20,height:10,channels:3,background:'blue'}}).png().toBuffer();const r=await fetch(origin+'/api/media',{method:'POST',headers:{Cookie:this.cookie,Origin:origin,'Content-Type':'image/png','X-Community-Request':'1','X-CSRF-Token':this.csrf,'X-Upload-ID':crypto.randomUUID()},body:png});assert.equal(r.status,201);return (await r.json()).image.id;}};}
 const a=client(),b=client(),c=client(),outsider=client(),guest=client();for(const [u,h]of[[a,'poll_host'],[b,'poll_writer'],[c,'poll_voter'],[outsider,'poll_other']])assert.equal((await u.req('/api/register','POST',{handle:h,name:h,password:'Poll-test-only-123'})).status,201);
 const club=await a.req('/api/clubs','POST',{name:'Private polls',description:'',access:'request'}),root='/api/clubs/'+club.id;for(const u of[b,c]){await u.req(root+'/join','POST',{});await a.req(root+'/decision','POST',{userId:u.id,decision:'approve'});}
 const input={title:'Что сыграем <img src=x>?',body:'Соберёмся вместе.',options:['Ущелье','ARAM','Дуэль'],durationHours:1,clientId:'poll-create-stable-001'};
 assert.equal((await guest.req(root+'/polls','POST',input)).status,401);assert.equal((await outsider.req(root+'/polls','POST',input)).status,403);assert.equal((await b.req(root+'/polls','POST',{...input,options:['ARAM','aram']})).status,422);assert.equal((await b.req(root+'/polls','POST',{...input,durationHours:169})).status,422);assert.equal((await b.req(root+'/polls','POST',{...input,options:['one']})).status,422);
 const creates=await Promise.all([b.req(root+'/polls','POST',input),b.req(root+'/polls','POST',input)]);assert.deepEqual(creates.map(x=>x.status).sort(),[200,201]);const id=creates[0].id,path='/api/posts/'+id+'/poll';assert.equal((await b.req(root+'/polls','POST',{...input,options:['Changed','Second']})).status,409);assert.equal((await a.req(root+'/posts')).posts.length,1);assert.equal((await guest.req(path)).status,403);assert.equal((await outsider.req(path)).status,403);assert.equal((await b.req('/api/posts/'+id,'PATCH',{title:'Change question',body:'New',version:1,clientId:'poll-edit-blocked-001'})).status,409);
 assert.equal((await guest.req(path+'/vote','PUT',{optionId:0})).status,401);assert.equal((await outsider.req(path+'/vote','PUT',{optionId:0})).status,403);assert.equal((await b.req(path+'/vote','PUT',{optionId:6})).status,422);
 const votes=await Promise.all([b.req(path+'/vote','PUT',{optionId:0}),b.req(path+'/vote','PUT',{optionId:1})]);assert.deepEqual(votes.map(x=>x.status).sort(),[200,409]);let result=(await b.req(path)).poll;assert.equal(result.total,1);const chosen=result.myOption;assert.equal((await b.req(path+'/vote','PUT',{optionId:chosen})).poll.total,1);await c.req(path+'/vote','PUT',{optionId:2});assert.equal((await a.req(path)).poll.total,2);assert(!JSON.stringify((await a.req(path)).poll).includes(c.id));
 await a.req('/api/blocks','POST',{userId:c.id});assert.equal((await a.req(path)).poll.total,1);await a.req('/api/blocks','DELETE',{userId:c.id});assert.equal((await a.req(path)).poll.total,2);
 await app.close();app=await createApp({databasePath,now:()=>clock});origin=await app.listen();assert.equal((await b.req(path)).poll.myOption,chosen);clock+=3600000;assert.equal((await a.req(path)).poll.closed,true);assert.equal((await a.req('/api/feed')).posts[0].poll.closed,true);assert.equal((await a.req(path+'/vote','PUT',{optionId:0})).status,409);assert.equal((await b.req(path+'/vote','PUT',{optionId:chosen})).status,200);assert.equal((await b.req(root+'/polls','POST',input)).id,id);
 await c.req(root+'/leave','POST',{});assert.equal((await c.req(path)).status,403);assert.equal((await a.req(path)).poll.total,1);assert.equal((await c.req('/api/feed')).posts.length,0);await a.req(root+'/ban','POST',{userId:b.id});assert.equal((await b.req(path)).status,403);assert.equal((await b.req(path+'/vote','PUT',{optionId:chosen})).status,403);assert.equal((await a.req(path)).poll.total,0);
 const open=await a.req('/api/clubs','POST',{name:'Public polls',description:'',access:'open'}),publicRoot='/api/clubs/'+open.id,pub=await a.req(publicRoot+'/polls','POST',{...input,clientId:'poll-public-stable-001'});assert.equal((await guest.req('/api/posts/'+pub.id+'/poll')).poll.total,0);assert.equal((await outsider.req('/api/posts/'+pub.id+'/poll/vote','PUT',{optionId:0})).status,403);await a.req('/api/posts/'+pub.id+'/poll/vote','PUT',{optionId:0});await a.req('/api/posts/'+pub.id,'DELETE',{});const d=openDatabase(databasePath);assert.equal(d.prepare('SELECT count(*) n FROM polls WHERE post_id=?').get(pub.id).n,0);assert.equal(d.prepare('SELECT count(*) n FROM poll_options WHERE post_id=?').get(pub.id).n,0);assert.equal(d.prepare('SELECT count(*) n FROM poll_votes WHERE post_id=?').get(pub.id).n,0);assert.deepEqual(d.prepare('PRAGMA foreign_key_check').all(),[]);d.close();
});
