import test from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,rmSync,readFileSync,copyFileSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {DatabaseSync} from 'node:sqlite';import sharp from 'sharp';import {openDatabase} from '../database.mjs';import {createApp} from '../app.mjs';
test('schema15→16 preserves posts, drafts, cold copy and reopens',()=>{const dir=mkdtempSync(join(tmpdir(),'wr-edit-schema-'));try{const p=join(dir,'db');let d=new DatabaseSync(p);d.exec(readFileSync(new URL('./fixtures/schema-v15.sql',import.meta.url),'utf8'));d.exec("INSERT INTO users(id,handle,name,password,created_at) VALUES('u','keep','Keep','unchanged',1);INSERT INTO clubs(id,owner_id,name,description,access,created_at) VALUES('c','u','Keep','','request',1);INSERT INTO memberships VALUES('c','u','member');INSERT INTO posts(club_id,author_id,title,body,created_at) VALUES('c','u','Title','Keep body',1);INSERT INTO post_drafts VALUES('c','u','Draft','Private',NULL,2,1)");d.close();copyFileSync(p,join(dir,'backup'));for(let i=0;i<2;i++){d=openDatabase(p);assert.equal(d.prepare('PRAGMA user_version').get().user_version,25);assert.equal(d.prepare('SELECT edit_version FROM posts').get().edit_version,1);assert.equal(d.prepare('SELECT body FROM post_drafts').get().body,'Private');assert.equal(d.prepare('SELECT body FROM posts').get().body,'Keep body');assert.equal(d.prepare('PRAGMA integrity_check').get().integrity_check,'ok');assert.deepEqual(d.prepare('PRAGMA foreign_key_check').all(),[]);d.close();}d=new DatabaseSync(join(dir,'backup'),{readOnly:true});assert.equal(d.prepare('PRAGMA user_version').get().user_version,15);d.close();}finally{rmSync(dir,{recursive:true,force:true});}});
test('post edit/search privacy, literal Unicode search, pagination, CAS, retry and revocation',async t=>{
const dir=mkdtempSync(join(tmpdir(),'wr-post-management-')),databasePath=join(dir,'db');let app=await createApp({databasePath}),origin=await app.listen();t.after(async()=>{await app.close();rmSync(dir,{recursive:true,force:true});});
 function client(){return {cookie:'',csrf:'',async req(path,method='GET',body){const headers={Cookie:this.cookie};if(method!=='GET')Object.assign(headers,{Origin:origin,'Content-Type':'application/json','X-Community-Request':'1','X-CSRF-Token':this.csrf});const r=await fetch(origin+path,{method,headers,body:body===undefined?undefined:JSON.stringify(body)}),d=r.headers.get('content-type')?.includes('application/json')?await r.json():{};if(r.headers.has('set-cookie'))this.cookie=r.headers.get('set-cookie').split(';')[0];if(d.csrf)this.csrf=d.csrf;if(d.user)this.id=d.user.id;return {...d,status:r.status};},async image(){const png=await sharp({create:{width:20,height:10,channels:3,background:'blue'}}).png().toBuffer();const r=await fetch(origin+'/api/media',{method:'POST',headers:{Cookie:this.cookie,Origin:origin,'Content-Type':'image/png','X-Community-Request':'1','X-CSRF-Token':this.csrf,'X-Upload-ID':crypto.randomUUID()},body:png});assert.equal(r.status,201);return (await r.json()).image.id;}};}

const a=client(),b=client(),c=client(),guest=client();for(const [u,h]of[[a,'post_host'],[b,'post_writer'],[c,'post_other']])assert.equal((await u.req('/api/register','POST',{handle:h,name:h,password:'Post-test-only-123'})).status,201);
const club=await a.req('/api/clubs','POST',{name:'Private club',description:'',access:'request'}),root='/api/clubs/'+club.id;for(const u of[b,c]){await u.req(root+'/join','POST',{});await a.req(root+'/decision','POST',{userId:u.id,decision:'approve'});}
const image=await b.image(),p=await b.req(root+'/posts','POST',{title:'Ренгар 100%',body:'Исходный текст',imageId:image,clientId:'post-create-stable-001'}),path='/api/posts/'+p.id;const edit={title:'РЕНГАР 100% <img src=x>',body:'Новый текст',version:1,clientId:'post-edit-stable-001'};
assert.equal((await guest.req(path,'PATCH',edit)).status,401);assert.equal((await a.req(path,'PATCH',edit)).status,403);assert.equal((await c.req(path,'PATCH',edit)).status,403);assert.equal((await b.req(path,'PATCH',{...edit,imageId:null})).status,422);
const pair=await Promise.all([b.req(path,'PATCH',edit),b.req(path,'PATCH',{...edit,clientId:'post-edit-stable-002'})]);assert.deepEqual(pair.map(x=>x.status).sort(),[200,409]);const accepted=pair[0].status===200?edit:{...edit,clientId:'post-edit-stable-002'};assert.equal((await b.req(path,'PATCH',accepted)).version,2);assert.equal((await b.req(path,'PATCH',{...accepted,body:'changed same key'})).status,409);
let post=(await b.req(path)).post;assert.equal(post.edit_version,2);assert.ok(post.edited_at);assert.equal(post.image_id,image);assert.equal(post.created_at,(await a.req(root+'/posts')).posts[0].created_at);
const search=q=>'/api/posts/search?q='+encodeURIComponent(q);assert.equal((await a.req(search('ренгар 100%'))).posts.length,1);assert.equal((await guest.req(search('ренгар'))).posts.length,0);assert.equal((await b.req(search('_'))).posts.length,0);assert.equal((await b.req('/api/posts/search?q=')).status,422);assert.equal((await b.req(search('ренгар')+'&before=x')).status,422);
const db=openDatabase(databasePath);for(let i=0;i<23;i++)db.prepare('INSERT INTO posts(club_id,author_id,title,body,created_at) VALUES(?,?,?,?,?)').run(club.id,b.id,'Пагинация '+i,'Text',1);db.close();const page=await a.req(search('пагинация'));assert.equal(page.posts.length,20);const next=await a.req(search('пагинация')+'&before='+page.next);assert.equal(next.posts.length,3);assert.equal(new Set([...page.posts,...next.posts].map(x=>x.id)).size,23);
await c.req('/api/blocks','POST',{userId:b.id});assert.equal((await c.req(search('ренгар'))).posts.length,0);
await app.close();app=await createApp({databasePath});origin=await app.listen();assert.equal((await b.req(path)).post.edit_version,2);assert.equal((await b.req(path,'PATCH',{...edit,version:2,title:'После перезапуска',clientId:'post-edit-stable-003'})).version,3);assert.equal((await b.req(path,'PATCH',edit)).status,409);
await b.req(root+'/leave','POST',{});assert.equal((await b.req(path,'PATCH',{...edit,version:3,clientId:'post-edit-stable-004'})).status,403);assert.equal((await b.req(search('пагинация'))).posts.length,0);assert.equal((await b.req(search('x')+'&club='+club.id)).status,403);assert.equal((await b.req('/api/media/'+image)).status,403);
const open=await a.req('/api/clubs','POST',{name:'Public club',description:'',access:'open'});await a.req('/api/clubs/'+open.id+'/posts','POST',{title:'Публичная тема',body:'Ренгар',clientId:'post-public-stable-001'});assert.equal((await guest.req(search('ренгар'))).posts.length,1);
});
