import test from 'node:test';import assert from 'node:assert/strict';import {openDatabase} from '../database.mjs';import {tournamentRoutes} from '../tournaments.mjs';import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
function fixture(){const db=openDatabase(':memory:');let time=1800000000000;for(let i=0;i<4;i++)db.prepare('INSERT INTO users(id,handle,name,password,created_at) VALUES(?,?,?,?,0)').run('s'+i,'schedule'+i,'Player','unused');
 db.exec("INSERT INTO tournaments(id,owner_id,title,description,capacity,state,client_id,signature,created_at) VALUES(1,'s0','Schedule cup','',4,'running','schedule-fixture','s',0);INSERT INTO tournament_teams(id,tournament_id,captain_id,name) VALUES(1,1,'s1','Alpha'),(2,1,'s2','Beta');INSERT INTO tournament_roster VALUES(1,1,'s1','accepted'),(1,2,'s2','accepted');INSERT INTO tournament_matches(tournament_id,round,slot,team_a,team_b) VALUES(1,1,0,1,2);");
 const req=(path,body={},uid='s0',method='POST')=>{let response;try{tournamentRoutes({db,user:uid?{id:uid}:null,path:new URL(path,'https://example.test').pathname,method,body,url:new URL(path,'https://example.test'),now:()=>time,send:(status,data)=>response={status,...data}});return response;}catch(e){return {status:e.status};}};return {db,req,get time(){return time},set time(v){time=v}};}
test('schedule permission, date validation, idempotency, stale forms, private inbox and read markers',()=>{const f=fixture(),{db,req}=f;try{const path='/api/tournaments/1/schedule',body={round:1,slot:0,startsAt:f.time+3600000,expectedVersion:0};
 assert.equal(req(path,body,null).status,401);assert.equal(req(path,body,'s1').status,403);assert.equal(req(path,{...body,startsAt:f.time}).status,422);assert.equal(req(path,body).status,200);assert.equal(req(path,body).status,200);assert.equal(db.prepare('SELECT count(*) n FROM tournament_notifications').get().n,2);
 const list=()=>req('/api/tournaments/notifications',{},'s1','GET');assert.equal(list().unread,1);assert.equal(req('/api/tournaments/notifications',{},'s3','GET').notifications.length,0);assert.equal(req('/api/tournaments/notifications',{},null,'GET').status,401);
 const n=list().notifications[0];assert.equal(req('/api/tournaments/notifications/'+n.id+'/read',{},'s3').status,404);assert.equal(req('/api/tournaments/notifications/'+n.id+'/read',{},'s1').status,200);assert.equal(list().unread,0);
 assert.equal(req(path,{...body,startsAt:f.time+7200000}).status,409);assert.equal(req(path,{...body,startsAt:f.time+7200000,expectedVersion:1}).status,200);assert.equal(list().notifications.length,1);assert.equal(list().notifications[0].kind,'rescheduled');
 db.prepare("INSERT INTO blocks(blocker_id,target_id) VALUES('s0','s1')").run();assert.equal(list().notifications.length,0);db.exec('DELETE FROM blocks');
 db.prepare("UPDATE tournament_roster SET status='declined' WHERE user_id='s1'").run();assert.equal(list().notifications.length,0);
 assert.equal(req('/api/tournaments/1/results',{round:1,slot:0,scoreA:1,scoreB:0}).status,200);assert.equal(req(path,{...body,expectedVersion:2,startsAt:f.time+10800000}).status,409);
}finally{db.close();}});
test('reminders materialize once within 30 minutes, reset on reschedule and disappear after completion or start',()=>{const f=fixture(),{db,req}=f;try{let starts=f.time+3600000;req('/api/tournaments/1/schedule',{round:1,slot:0,startsAt:starts,expectedVersion:0});const list=()=>req('/api/tournaments/notifications',{},'s1','GET');assert.equal(list().notifications.length,1);f.time=starts-1800000;assert.equal(list().notifications.filter(n=>n.kind==='reminder').length,1);list();assert.equal(db.prepare("SELECT count(*) n FROM tournament_notifications WHERE user_id='s1' AND kind='reminder'").get().n,1);
 starts=f.time+7200000;req('/api/tournaments/1/schedule',{round:1,slot:0,startsAt:starts,expectedVersion:1});assert.equal(list().notifications.length,1);f.time=starts-1000;assert.equal(list().notifications.filter(n=>n.kind==='reminder').length,1);f.time=starts;assert.equal(list().notifications.filter(n=>n.kind==='reminder').length,0);
}finally{db.close();}});
test('schema25 migration preserves teams, match results and accounts and survives reopening',()=>{const dir=mkdtempSync(join(tmpdir(),'wr-schedule-')),file=join(dir,'db.sqlite');try{let db=openDatabase(file);db.exec("INSERT INTO users(id,handle,name,password,created_at) VALUES('keep','keep','Keep','hash',0);INSERT INTO tournaments(id,owner_id,title,description,capacity,client_id,signature,created_at) VALUES(1,'keep','Keep cup','',4,'keep-fixture','s',0);INSERT INTO tournament_matches(tournament_id,round,slot,score_a) VALUES(1,1,0,3);ALTER TABLE tournament_matches DROP COLUMN ready_a_at; ALTER TABLE tournament_matches DROP COLUMN ready_b_at; DROP TABLE tournament_notifications;ALTER TABLE tournament_matches DROP COLUMN starts_at;ALTER TABLE tournament_matches DROP COLUMN schedule_version;PRAGMA user_version=25;");db.close();db=openDatabase(file);assert.equal(db.prepare('PRAGMA user_version').get().user_version,27);assert.equal(db.prepare('SELECT password FROM users').get().password,'hash');assert.equal(db.prepare('SELECT score_a,starts_at FROM tournament_matches').get().score_a,3);assert.equal(db.prepare('PRAGMA foreign_key_check').all().length,0);db.close();db=openDatabase(file);assert.equal(db.prepare('SELECT count(*) n FROM tournaments').get().n,1);db.close();}finally{rmSync(dir,{recursive:true,force:true});}});
