import test from 'node:test';import assert from 'node:assert/strict';import {openDatabase} from '../database.mjs';import {tournamentRoutes} from '../tournaments.mjs';import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
function fixture(){const db=openDatabase(':memory:');let time=1800000000000;for(let i=0;i<5;i++)db.prepare('INSERT INTO users(id,handle,name,password,created_at) VALUES(?,?,?,?,0)').run('r'+i,'ready'+i,'Player','unused');
 db.exec("INSERT INTO tournaments(id,owner_id,title,description,capacity,state,client_id,signature,created_at) VALUES(1,'r0','Ready cup','',4,'running','ready-fixture','s',0);INSERT INTO tournament_teams(id,tournament_id,captain_id,name) VALUES(1,1,'r1','Alpha'),(2,1,'r2','Beta'),(3,1,'r3','Other');INSERT INTO tournament_roster VALUES(1,1,'r1','accepted'),(1,2,'r2','accepted'),(1,3,'r3','accepted'),(1,1,'r4','accepted');INSERT INTO tournament_matches(tournament_id,round,slot,team_a,team_b) VALUES(1,1,0,1,2);");
 const req=(path,body={},uid='r0',method='POST')=>{let response;try{tournamentRoutes({db,user:uid?{id:uid}:null,path,method,body,url:new URL(path,'https://example.test'),now:()=>time,send:(status,data)=>response={status,...data}});return response;}catch(e){return {status:e.status};}};return {db,req,get time(){return time},set time(v){time=v}};}
test('only participating captains confirm once; stale requests cannot restore readiness after reschedule',()=>{const f=fixture(),{db,req}=f;try{const ready='/api/tournaments/1/ready',body={round:1,slot:0,expectedVersion:1},match=()=>db.prepare('SELECT * FROM tournament_matches').get();
 assert.equal(req(ready,body,null).status,401);assert.equal(req(ready,body,'r1').status,409);assert.equal(req('/api/tournaments/1/schedule',{round:1,slot:0,expectedVersion:0,startsAt:f.time+3600000}).status,200);
 for(const uid of ['r0','r3','r4'])assert.equal(req(ready,body,uid).status,403);
 assert.equal(req(ready,body,'r1').status,200);const first=match().ready_a_at;f.time+=1000;assert.equal(req(ready,body,'r1').status,200);assert.equal(match().ready_a_at,first);assert.equal(match().ready_b_at,null);
 assert.equal(req(ready,body,'r2').status,200);assert.ok(match().ready_b_at);const detail=req('/api/tournaments/1',{},'r0','GET');assert.equal(detail.matches[0].ready_a_at,first);
 // Repeating the same scheduled time does not clear confirmations.
 const at=match().starts_at;req('/api/tournaments/1/schedule',{round:1,slot:0,expectedVersion:0,startsAt:at});assert.equal(match().ready_a_at,first);
 req('/api/tournaments/1/schedule',{round:1,slot:0,expectedVersion:1,startsAt:at+3600000});assert.equal(match().ready_a_at,null);assert.equal(match().ready_b_at,null);assert.equal(req(ready,body,'r1').status,409);assert.equal(match().ready_a_at,null);
 assert.equal(req(ready,{...body,expectedVersion:2},'r1').status,200);
 db.exec("INSERT INTO blocks(blocker_id,target_id) VALUES('r1','r2')");assert.equal(req(ready,{...body,expectedVersion:2},'r2').status,404);db.exec('DELETE FROM blocks');
 req('/api/tournaments/1/results',{round:1,slot:0,scoreA:2,scoreB:1});assert.equal(req(ready,{...body,expectedVersion:2},'r2').status,409);
 assert.equal(req(ready,{...body,slot:-1},'r1').status,422);
}finally{db.close();}});
test('schema26 migration keeps schedule, notifications and scores with initially unconfirmed readiness',()=>{const dir=mkdtempSync(join(tmpdir(),'wr-ready-')),file=join(dir,'db.sqlite');try{let db=openDatabase(file);db.exec("INSERT INTO users(id,handle,name,password,created_at) VALUES('keep','keep','Keep','hash',0);INSERT INTO tournaments(id,owner_id,title,description,capacity,client_id,signature,created_at) VALUES(1,'keep','Keep cup','',4,'keep-fixture','s',0);INSERT INTO tournament_matches(tournament_id,round,slot,score_a,starts_at,schedule_version) VALUES(1,1,0,3,1800000000000,2);INSERT INTO tournament_notifications(user_id,tournament_id,round,slot,schedule_version,kind,created_at) VALUES('keep',1,1,0,2,'scheduled',0);DROP TABLE event_waitlist;DROP TABLE notification_preferences;DROP TRIGGER club_post_notify;DROP TRIGGER club_post_leave;DROP TRIGGER club_post_membership;DROP TABLE club_post_notifications;DROP TABLE club_post_subscriptions;DROP TABLE tournament_roster_history; DROP TABLE tournament_result_history; ALTER TABLE tournament_teams DROP COLUMN withdrawn_at; ALTER TABLE tournament_teams DROP COLUMN withdraw_reason; ALTER TABLE tournament_matches DROP COLUMN result_version; ALTER TABLE tournament_matches DROP COLUMN result_kind; ALTER TABLE tournament_matches DROP COLUMN result_reason; ALTER TABLE tournament_matches DROP COLUMN ready_a_at;ALTER TABLE tournament_matches DROP COLUMN ready_b_at;PRAGMA user_version=26;");db.close();for(let i=0;i<2;i++){db=openDatabase(file);assert.equal(db.prepare('PRAGMA user_version').get().user_version,33);const m=db.prepare('SELECT * FROM tournament_matches').get();assert.equal(m.score_a,3);assert.equal(m.starts_at,1800000000000);assert.equal(m.schedule_version,2);assert.equal(m.ready_a_at,null);assert.equal(m.ready_b_at,null);assert.equal(db.prepare('SELECT count(*) n FROM tournament_notifications').get().n,1);assert.equal(db.prepare('SELECT password FROM users').get().password,'hash');assert.equal(db.prepare('PRAGMA foreign_key_check').all().length,0);db.close();}}finally{rmSync(dir,{recursive:true,force:true});}});
